<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$char        = chr(97 + $column);
$outerClass  = array('rex-form-col-'.$char, $element->getOuterClass());
$help        = $element->getHelpText() ? '<span class="sly-form-helptext">'.nl2br(rex_translate($element->getHelpText())).'</span>' : '';
$isContainer = $element->isContainer();
$label       = $element->getLabel();
$label       = empty($label) ? '&nbsp;' : rex_translate($label).':';
$label       = preg_replace('#\*\*(.*?)\*\*#i', '<strong>$1</strong>', $label);
$label       = preg_replace('#__(.*?)__#i', '<em>$1</em>', $label);
$label       = preg_replace('#//(.*?)//#i', '<em>$1</em>', $label);

// Elemente einrücken

if (preg_match('#^( *)#', $label, $matches)) {
	$label = preg_replace('#^( *)#', str_repeat('&nbsp;', strlen($matches[1])), $label);
}

if ($isContainer) {
	print $element->render();
}
else {
	?>
	<p class="<?= implode(' ', $outerClass) ?>">
		<label for="<?= $element->getID() ?>"><?= $label ?></label>
		<?= $element->render() ?>
		<?= $help ?>
	</p>
	<?php
}
