<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$nativeFocus = sly_Helper_Modernizr::hasInput('autofocus');
$attributes  = array(
	'class'   => implode(' ', $this->classes),
	'method'  => strtolower($this->method),
	'action'  => $this->action,
	'id'      => $this->id,
	'enctype' => $this->enctype
);

if (!empty($this->focussedElement) && $nativeFocus) {
	$el = $this->findElementByID($this->focussedElement);
	if ($el) $el->setAttribute('autofocus', 'autofocus');
}

?>

<div class="sly-form">
	<?php if (!$omitFormTag): ?>
	<form <?php echo sly_Util_HTML::buildAttributeString($attributes) ?>>
	<?php endif ?>
		<?php if (!empty($this->hiddenValues)): ?>
		<div>
			<?php
			foreach ($this->hiddenValues as $name => $value) {
				$value['type'] = 'hidden';
				$value['name'] = $name;
				print '<input '.sly_Util_HTML::buildAttributeString($value).' />';
			}
			?>
		</div>
		<?php endif ?>

		<?php
		$hasButtonBar = $this->submitButton || $this->resetButton || $this->applyButton || $this->deleteButton;

		if ($hasButtonBar) {
			$fieldset = end($this->fieldsets);
			if (!$fieldset) $fieldset = $this->beginFieldset($this->title);
			print $this->renderView('buttons.phtml', array('fieldset' => $fieldset, 'hasButtonBar' => $hasButtonBar));
		}

		foreach ($this->fieldsets as $i => $fieldset) {
			print $fieldset->render();
		}
		?>
	<?php if (!$omitFormTag): ?>
	</form>
	<?php endif ?>
</div>

<?php if (!empty($this->focussedElement) && !$nativeFocus): ?>
<script type="text/javascript">
document.getElementById('<?php echo $this->focussedElement ?>').focus();
</script>
<?php endif ?>
