<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$formRowClass[] = $element->getFormRowClass();
$class          = implode(' ', array_filter($formRowClass));
$attributes     = compact('class', 'rel', 'style');
$column         = 0;

print '<div '.sly_Util_HTML::buildAttributeString($attributes).'>';
print $this->renderView('element.phtml', compact('element', 'column'));
print '</div>';
