<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<!DOCTYPE html>
<html<?= !empty($this->language) ? ' lang="'.$this->language.'"' : '' ?><?= !empty($this->manifest) ? ' manifest="'.$this->manifest.'"' : '' ?>>
<head><?php
	if (!empty($this->base)) {
		print "\n\t<base href=\"".$this->base."\" />";
	}

	print "\n\t<title>".sly_html(trim($this->title))."</title>\n";

	if (!empty($this->charset)) {
		print "\t<meta charset=\"".$this->charset."\" />\n";
	}

	sly_Core::dispatcher()->notify('PAGE_HEADER', '');

	if ($this->favIcon !== null) {
		$this->addLink('shortcut icon', $this->favIcon, 'image/x-icon');
	}

	$this->printHttpMetas();
	$this->printMetas();
	$this->printLinks();
	$this->printCSSFiles();
	if (!$this->scriptsAtBottom) $this->printJavaScriptFiles();
	$this->printCSS();
	if (!$this->scriptsAtBottom) $this->printJavaScript();
?></head>
<body<?= $this->printBodyAttrs() ?>>
