<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $rex_user_loginmessage;

if (!empty($rex_user_loginmessage)) {
	print rex_warning($rex_user_loginmessage);
}
elseif (!empty($this->message)) {
	print rex_warning($this->message);
}

$form = new sly_Form('index.php', 'POST', t('login_title'), '', 'loginformular');
$form->addHiddenValue('page', 'login');
$form->addHiddenValue('func', 'login');
$form->addHiddenValue('javascript', 0, 'javascript');
$form->addHiddenValue('referer', isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '');

$form->add(new sly_Form_Input_Text('rex_user_login', t('login_name'), ''));
$form->add(new sly_Form_Input_Password('rex_user_psw', t('login_password'), ''));

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('login'));
print $form->render();

?>

<? if (!empty($rex_user_loginmessage)): ?>
<script type="text/javascript">sly.startLoginTimer('<?= addslashes(t('login_welcome')) ?>');</script>
<? endif ?>
