<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$user = sly_Util_User::getCurrentUser();

if ($user && $this->hasNavigation()) {
	$user_name = $user->getName() != '' ? $user->getName() : $user->getLogin();
	?>
	<ul class="sly-meta">
		<li class="rex-navi-first"><span><?= t('logged_in_as').' '.htmlspecialchars($user_name) ?></span></li>
		<li><a href="index.php?page=profile"><?= t('profile_title') ?></a></li>
		<li><a href="index.php?page=login&amp;func=logout"><?= t('logout') ?></a></li>
		<li><a href="../">zur Website</a></li>
	</ul>
	<?php
}
elseif ($this->hasNavigation()) {
	echo '<p class="sly-meta">'.t('logged_out').'</p>';
}
else {
	echo '<p class="sly-meta">&nbsp;</p>';
}
