<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

if ($article->isStartArticle()) {
	$sprite = 'article-startpage';
}
else {
	$sprite = 'article';
}

$base_url     = 'index.php?page=content&article_id='.$article->getId().'&clang='.$this->clangId;
$edit_url     = 'index.php?page=structure&amp;category_id='.$article->getCategoryId().'&amp;clang='.$this->clangId.'&amp;edit_id='.$article->getId();
$status       = $statusTypes[$article->getStatus()][0];
$status_class = $statusTypes[$article->getStatus()][1];

$service  = sly_Service_Factory::getArticleTypeService();
$type     = $article->getType();

if ($type) {
	if ($service->exists($type)) $type = $service->getTitle($type);
	else $type = '('.$type.')';
}
else {
	$type = t('option_no_type');
}

if ($this->canPublishCategory($this->categoryId) && $this->categoryId != $article->getId()) {
	$status = '<a href="'.$edit_url.'&amp;func=editStatusArticle" class="'.$status_class.'">'.$status.'</a>';
}
else {
	$status_class .= ' rex-strike';
	$status = '<span class="'.$status_class.'">'.$status.'</span>';
}
?>
<tr>
	<td class="sly-icon"><?php echo sly_Util_HTML::getSpriteLink($base_url, $article->getName(), $sprite) ?></td>
	<td class="name"><a href="<?php echo sly_html($base_url) ?>"><?php echo sly_html($article->getName()) ?></a></td>
	<td class="arttype"><?php echo sly_html($type) ?></td>
	<td class="prior"><?php echo sly_html($article->getPrior()) ?></td>
	<td class="status">
		<?php
		if ($canEdit) {
			echo '<a href="'.$edit_url.'&amp;func=editArticle">'.t('change').'</a>&nbsp;';
		} else {
			echo '<span class="rex-strike">'.t('change').'</span>&nbsp;';
		}
		if ($canEdit && !$article->isStartArticle()) {
			echo '<a href="'.$edit_url.'&amp;func=deleteArticle" class="sly-delete">'.t('delete').'</a>';
		} else {
			echo '<span class="rex-strike">'.t('delete').'</span>';
		}
		?>
		&nbsp;<?php echo $status ?>
	</td>
</tr>
