<form action="index.php" method="post" id="rex-form-structure-article">
	<fieldset>
		<input type="hidden" name="page" value="structure" />
		<input type="hidden" name="category_id" value="<?= $this->categoryId ?>" />
		<input type="hidden" name="clang" value="<?= $this->clangId ?>" />
		<input type="hidden" name="func" value="<?= $this->action ?>" />
	</fieldset>

	<?php
	$add_url = 'index.php?page=structure&category_id=' . $this->categoryId . '&clang=' . $this->clangId . '&func=addArticle';
	$add_article = sly_Util_HTML::getSpriteLink($add_url, t('add_article'), 'article-add');

	$table = new sly_Table();
	$table->addColumn(new sly_Table_Column($add_article, '40px', '', array('class' => 'sly-icon')));
	if ($advancedMode) {
		$table->addColumn(new sly_Table_Column(t('header_id'), '40px'));
	}
	$table->addColumn(new sly_Table_Column(t('header_article_name')));
	$table->addColumn(new sly_Table_Column(t('content_arttype'), '200px'));
	$table->addColumn(new sly_Table_Column(t('header_priority'), '40px'));
	$table->addColumn(new sly_Table_Column(t('header_status'), '150px'));

	$table->openBuffer();

	if ($this->renderAddArticle) {
		print $this->render(sly_Controller_Structure::$viewPath . 'article_table_row_add.phtml', array('advancedMode' => $advancedMode));
	}

	foreach ($articles as $article) {
		if ($this->renderEditArticle && $this->renderEditArticle == $article->getId()) {
			print $this->render(
				sly_Controller_Structure::$viewPath . 'article_table_row_edit.phtml',
				array('article' => $article, 'advancedMode' => $advancedMode)
			);
		}
		else {
			print $this->render(
				sly_Controller_Structure::$viewPath . 'article_table_row.phtml',
				array('article' => $article, 'advancedMode' => $advancedMode, 'statusTypes' => $statusTypes, 'canEdit' => $canEdit)
			);
		}
	}

	$table->closeBuffer();
	print $table->render();
	?>
</form>

