<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<tr class="active">
	<td class="sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', t('article_add'), 'article') ?></td>
	<td class="name" colspan="2"><input class="rex-form-text" type="text" id="sly-form-field-name" name="article_name" autofocus="autofocus" /></td>
	<td class="prior"><input class="rex-form-text" type="text" id="sly-form-field-prior" name="article_position" value="100" /></td>
	<td class="status"><input type="submit" name="do_add_article" value="<?php echo t('article_add') ?>" /></td>
</tr>
