<tr class="rex-table-row-activ">
	<td class="sly-icon"><?= sly_Util_HTML::getSpriteLink('', t('add_category'), 'category-add') ?></td>
	<?= $advancedMode ? '<td class="rex-small">-</td>' : '' ?>
	<td><input class="rex-form-text" type="text" id="sly-form-field-name" name="category_name" /></td>
	<td><input class="rex-form-text" type="text" id="sly-form-field-prior" name="category_position" value="100" /></td>
	<td><input type="submit" name="do_add_category" value="<?= t('add_category') ?>" /></td>
</tr>