<?php
$base_url     = 'index.php?page=structure&category_id='.$category->getId().'&clang='.$this->clangId;
$edit_url     = 'index.php?page=structure&amp;category_id='.$category->getParentId().'&amp;clang='.$this->clangId.'&amp;edit_id='.$category->getId();
$status       = $statusTypes[$category->getStatus()][0];
$status_class = $statusTypes[$category->getStatus()][1];

if ($this->canPublishCategory($category->getId())) {
	$status = '<a href="'.$edit_url.'&amp;func=editStatusCategory" class="'.$status_class.'">'.$status.'</a>';
}
else {
	$status_class .= ' rex-strike';
	$status = '<span class="'.$status_class.'">'.$status.'</span>';
}
?>
<tr>
	<td class="sly-icon"><?php echo sly_Util_HTML::getSpriteLink($base_url, $category->getCatName(), 'category') ?></td>
	<td class="name"><a href="<?php echo sly_html($base_url) ?>"><?php echo sly_html($category->getCatName()) ?></a></td>
	<td class="prior"><?php echo sly_html($category->getCatPrior()) ?></td>
	<td class="status">
		<?php
		if ($this->canEditCategory($category->getId())) {
			echo '<a href="'.$edit_url.'&amp;func=editCategory">'.t('change').'</a>&nbsp;';
			echo '<a href="'.$edit_url.'&amp;func=deleteCategory" class="sly-delete">'.t('delete').'</a>';
		}
		else {
			echo '<span class="rex-strike">'.t('change').'</span>&nbsp;';
			echo '<span class="rex-strike">'.t('delete').'</span>';
		}
		?>
		&nbsp;<?php echo $status ?>
	</td>
</tr>
