<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<form action="index.php" method="post" id="sly-form-structure-category">
	<fieldset>
		<input type="hidden" name="page" value="structure" />
		<input type="hidden" name="category_id" value="<?php echo $this->categoryId ?>" />
		<input type="hidden" name="clang" value="<?php echo $this->clangId ?>" />
		<input type="hidden" name="func" value="<?php echo $this->action ?>" />
	</fieldset>

	<?php
	$add_url = '';
	if ($this->canEditCategory($this->categoryId)) {
		$add_url = 'index.php?page=structure&category_id='.$this->categoryId.'&clang='.$this->clangId.'&func=addCategory';
	}
	$add_category = sly_Util_HTML::getSpriteLink($add_url, t('add_category'), 'category-add');

	$table = new sly_Table();
	$table->addColumn(new sly_Table_Column($add_category, '', '', array('class' => 'sly-icon')));
	$table->addColumn(new sly_Table_Column(t('category'), '', '', array('class' => 'name')));

	$isActive = $this->renderAddCategory || $this->renderEditCategory;

	if ($isActive) {
		$table->addClass('active');
		$table->addColumn(new sly_Table_Column(t('position_short'), '', '', array('class' => 'pos')));
	}

	$table->addColumn(new sly_Table_Column(t('status'), '', '', array('class' => 'status')));
	$table->openBuffer();

	if ($this->categoryId != 0 && $currentCategory) {
		?>
		<tr>
			<td class="sly-icon">&nbsp;</td>
			<td class="name"><a href="index.php?page=structure&amp;category_id=<?php echo $currentCategory->getParentId().'&amp;clang='.$this->clangId ?>">..</a></td>
			<?php if ($isActive): ?><td class="pos">&nbsp;</td><?php endif ?>
			<td class="status">&nbsp;</td>
		</tr>
		<?php
	}

	if ($this->renderAddCategory) {
		print $this->render(
			sly_Controller_Structure::$viewPath.'category_table_row_add.phtml',
			array('maxCatPosition' => $maxCatPosition)
		);
	}

	foreach ($categories as $category) {
		if ($this->renderEditCategory && $this->renderEditCategory == $category->getId()) {
			print $this->render(
				sly_Controller_Structure::$viewPath.'category_table_row_edit.phtml',
				array('category' => $category, 'maxCatPosition' => $maxCatPosition)
			);
		}
		elseif ($this->canViewCategory($category->getId())) {
			print $this->render(
				sly_Controller_Structure::$viewPath.'category_table_row.phtml',
				array('category' => $category, 'statusTypes' => $statusTypes, 'isActive' => $isActive)
			);
		}
	}

	if (!$this->renderAddCategory && !$currentCategory && empty($categories)) {
		?>
		<tr>
			<td colspan="<?php echo $isActive ? 5 : 4 ?>" class="sly-icon"><?php echo t('no_categories_yet') ?></td>
		</tr>
		<?php
	}

	$table->closeBuffer();
	print $table->render();
	?>
</form>

