<form action="index.php" method="post" id="rex-form-structure-category">
	<fieldset>
		<input type="hidden" name="page" value="structure" />
		<input type="hidden" name="category_id" value="<?= $this->categoryId ?>" />
		<input type="hidden" name="clang" value="<?= $this->clangId ?>" />
		<input type="hidden" name="func" value="<?= $this->action ?>" />
	</fieldset>

	<?php
	$add_url      = 'index.php?page=structure&category_id='.$this->categoryId.'&clang='.$this->clangId.'&func=addCategory';
	$add_category = sly_Util_HTML::getSpriteLink($add_url, t('add_category'), 'category-add');

	$table = new sly_Table();
	$table->addColumn(new sly_Table_Column($add_category, '', '', array('class' => 'sly-icon')));
	if ($advancedMode) {
		$table->addColumn(new sly_Table_Column(t('header_id'), '', '', array('class' => 'id')));
	}
	$table->addColumn(new sly_Table_Column(t('header_category'), '', '', array('class' => 'name')));
	$table->addColumn(new sly_Table_Column(t('header_priority'), '', '', array('class' => 'prior')));
	$table->addColumn(new sly_Table_Column(t('header_status'), '', '', array('class' => 'status')));

	$table->openBuffer();

	if ($this->categoryId != 0 && $currentCategory) {
		echo '<tr>';
		echo '<td class="sly-icon">&nbsp;</td>';
		if ($advancedMode) {
			echo '<td class="id">'.t('header_id').'</td>';
		}

		echo '<td class="name"><a href="index.php?page=structure&amp;category_id='.$currentCategory->getParentId().'&amp;clang='.$this->clangId.'">..</a></td>';
		echo '<td class="prior">&nbsp;</td>';
		echo '<td class="status">&nbsp;</td>';
		echo '</tr>';
	}

	if ($this->renderAddCategory) {
		print $this->render(sly_Controller_Structure::$viewPath.'category_table_row_add.phtml', array('advancedMode' => $advancedMode));
	}

	foreach ($categories as $category) {
		if ($this->renderEditCategory && $this->renderEditCategory == $category->getId()) {
			print $this->render(
				sly_Controller_Structure::$viewPath.'category_table_row_edit.phtml',
				array('category' => $category, 'advancedMode' => $advancedMode)
			);
		}
		else {
			print $this->render(
				sly_Controller_Structure::$viewPath.'category_table_row.phtml',
				array('category' => $category, 'advancedMode' => $advancedMode, 'statusTypes' => $statusTypes)
			);
		}
	}

	$table->closeBuffer();
	print $table->render();
	?>
</form>

