<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<tr class="active">
	<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', t('add_category'), 'category-add') ?></td>
	<td class="sly-col-name sly-has-input"><div><input class="sly-form-text" type="text" name="category_name" autofocus="autofocus" required="required" placeholder="<?php echo ht('category') ?>" /></div></td>
	<td class="sly-col-pos sly-has-input"><div><input class="sly-form-text" type="number" name="category_position" min="1" max="<?php echo $maxCatPosition+1 ?>" required="required" value="<?php echo $maxCatPosition+1 ?>" /></div></td>
	<td class="sly-col-status sly-has-input"><div><input type="submit" name="do_add_category" value="<?php echo t('add_category') ?>" /></div></td>
</tr>
