<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title('Setup: Sprachauswahl');

?>
<div class="sly-area">
	<h2>Bitte wählen Sie eine Sprache aus.</h2>
	<div class="sly-area-content">
		<ul class="sly-setup-language">
		<?php

		$langpath = SLY_SALLYFOLDER.'/backend/lang';
		$locales  = sly_I18N::getLocales($langpath);

		foreach ($locales as $l) {
			$i18n  = new sly_I18N($l, $langpath, false);
			$label = $i18n->msg('lang');

			print '<li><a href="index.php?func=license&amp;lang='.urlencode($l).'">'.sly_html($label).'</a></li>';
		}

		unset($i18n);

		?>
		</ul>
	</div>
</div>
