<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_config_title'));

if (!empty($this->warning)) print sly_Helper_Message::warn($this->warning);

$form = new sly_Form('index.php', 'POST', t('configuration'), '', 'rex-form-setup-step-4');
$this->printHiddens('config', $form);

// fields

$form->add(new sly_Form_Input_Text('projectname', t('project_name'), $projectName));

if (class_exists('DateTimeZone')) {
	$timezoneList   = DateTimeZone::listIdentifiers();
	$timezoneList   = array_combine($timezoneList, $timezoneList);
	$timezoneSelect = new sly_Form_Select_DropDown('timezone', t('timezone'), $timezone, $timezoneList);

	$form->add($timezoneSelect);
}

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_config_continue'));

// render it!

$form->setFocus('projectname');
print $form->render();
