<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_config_title'));

if (!empty($this->warning)) print rex_warning($this->warning);

$form = new sly_Form('index.php', 'POST', t('setup_config_header'), '', 'rex-form-setup-step-4');
$this->printHiddens('config', $form);

// fields

$form->add(new sly_Form_Input_Text('server', t('setup_config_server'), $server));
$form->add(new sly_Form_Input_Text('servername', t('setup_config_servername'), $serverName));
$form->add(new sly_Form_Input_Text('error_email', t('setup_config_error_email'), $errorEMail));
if(class_exists('DateTimeZone')) {
	$timezoneList = DateTimeZone::listIdentifiers();
	$timezoneList = array_combine($timezoneList, $timezoneList);
	$timezoneSelect = new sly_Form_Select_DropDown('timezone', t('setup_config_timezone'), $timezone, $timezoneList);
	$form->add($timezoneSelect);
}

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_config_continue'));

// render it!

$form->setFocus('server');
print $form->render();
