<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_step_n', 4, 5));

if (!empty($this->warning)) print sly_Helper_Message::warn($this->warning);

$form = new sly_Form('index.php', 'POST', t('settings'));
$this->printHiddens('config', $form);

// fields

$form->add(new sly_Form_Input_Text('projectname', t('project_name'), $projectName));
$form->add(sly_Form_Helper::getTimezoneSelect('timezone', $timezone));

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_continue_to_n', 5));

// render it!

$form->setFocus('projectname');
print $form->render();
