<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<!DOCTYPE html>
<html>
<head>
	<title>SallyCMS .htaccess-Test</title>
	<script src="../../js/jquery.min.js" type="text/javascript"></script>
	<script type="text/javascript">
	jQuery(function($) {
		$('#security_warning').show();
		$('#nextstep').hide();
	});
	</script>
</head>
<body>
	<p>Diese Seite d&uuml;rften Sie nie sehen.</p>
</body>
</html>
