<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_license_title'));

$license = SLY_BASE.'/_lizenz.txt';
$license = file_exists($license) ? file_get_contents($license) : t('setup_license_not_found');

?>
<div class="rex-area">
	<h2><?php print t('setup_license_header') ?></h2>

	<div class="rex-area-content">
		<h3><?php print t('setup_license_steps') ?></h3>
		<ul>
			<li><?php print t('setup_license_step_1') ?></li>
			<li><?php print t('setup_license_step_2') ?></li>
			<li><?php print t('setup_license_step_3') ?></li>
			<li><?php print t('setup_license_step_4') ?></li>
		</ul>
		<div class="rex-area-scroll">
			<p><?php print nl2br($license) ?></p>
		</div>
	</div>

	<div class="rex-area-footer">
		<p class="rex-algn-rght"><a href="index.php?page=setup&amp;func=fsperms&amp;lang=<?php print urlencode($this->lang) ?>">&raquo; <?php print t('setup_license_accept') ?></a></p>
	</div>
</div>
