<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$name = sly_html($this->getName());
$id   = sly_html($this->getID());
$articles = sly_makeArray($this->getDisplayValue());
$articles = array_filter($articles);
$values   = array();
$list     = array();

foreach ($articles as $articleID) {
	$fullName = sly_Form_Widget_Link::getFullName($articleID);
	if (empty($fullName)) continue;

	$values[] = $articleID;
	$list[]   = array($articleID, $fullName);
}

?>
<span class="sly-widget sly-linklist<?= isset($this->attributes['class']) ? ' '.sly_html($this->attributes['class']) : '' ?>">
	<input type="hidden" name="<?= $name ?>" id="<?= $id ?>" value="<?= sly_html(implode(',', $values)) ?>" />
	<select size="8" class="">
		<? foreach ($list as $element): ?>
		<option value="<?= sly_html($element[0]) ?>"><?= sly_html($element[1]) ?></option>
		<? endforeach ?>
	</select>

	<span class="sly-icons move">
		<a href="#" rel="top" title="<?= t('var_linklist_move_top') ?>"></a>
		<a href="#" rel="up" title="<?= t('var_linklist_move_up') ?>"></a>
		<a href="#" rel="down" title="<?= t('var_linklist_move_down') ?>"></a>
		<a href="#" rel="bottom" title="<?= t('var_linklist_move_bottom') ?>"></a>
	</span>

	<span class="sly-icons edit">
		<a href="#" rel="open" title="<?= t('var_link_open') ?>"></a>
		<a href="#" rel="delete" title="<?= t('var_link_remove') ?>"></a>
	</span>
</span>
