<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$value  = sly_makeArray($this->getDisplayValue());
$value  = array_filter($value);
$name   = $this->getAttribute('name');
$values = array();

foreach ($value as $idx => $id) {
	$article = sly_Util_Article::findById($id);
	if ($article) $values[$id] = $article->getName();
}

?>
<span class="sly-widget sly-linklist" data-id="<?= $name ?>">
	<input type="hidden" name="<?= $name ?>" id="<?= $name ?>" value="<?= sly_html(implode(',', array_keys($values))) ?>" />
	<select size="8" class="<?= $this->attributes['class'] ?>">
		<? foreach ($values as $id => $name): ?>
		<option value="<?= sly_html($id) ?>"><?= sly_html($name) ?></option>
		<? endforeach ?>
	</select>

	<span class="sly-icons move">
		<a href="#" rel="top"><img src="assets/file_top.png" title="<?= t('var_linklist_move_top') ?>" alt="" /></a>
		<a href="#" rel="up"><img src="assets/file_up.png" title="<?= t('var_linklist_move_up') ?>" alt="" /></a>
		<a href="#" rel="down"><img src="assets/file_down.png" title="<?= t('var_linklist_move_down') ?>" alt="" /></a>
		<a href="#" rel="bottom"><img src="assets/file_bottom.png" title="<?= t('var_linklist_move_bottom') ?>" alt="" /></a>
	</span>

	<span class="sly-icons edit">
		<a href="#" rel="open"><img src="assets/file_open.png" title="<?= t('var_link_open') ?>" alt="" /></a>
		<a href="#" rel="delete"><img src="assets/file_del.png" title="<?= t('var_link_remove') ?>" alt="" /></a>
	</span>
</span>
