<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$name   = sly_html($this->getName());
$id     = sly_html($this->getID());
$files  = sly_makeArray($this->getDisplayValue());
$files  = empty($files) ? array() : array_filter($files);
$values = array();
$list   = array();

foreach ($files as $filename) {
	$fullName = sly_Form_Widget_Media::getFullName($filename);
	if (empty($fullName)) continue;

	$values[] = $filename;
	$list[]   = array($filename, $fullName);
}

?>
<span class="sly-widget sly-medialist<?= isset($this->attributes['class']) ? ' '.sly_html($this->attributes['class']) : '' ?>">
	<input type="hidden" name="<?= $name ?>" id="<?= $id ?>" value="<?= sly_html(implode(',', $values)) ?>" />
	<select size="8">
		<?php foreach ($list as $element): ?>
		<option value="<?= sly_html($element[0]) ?>"><?= sly_html($element[1]) ?></option>
		<?php endforeach ?>
	</select>

	<span class="sly-icons move">
		<a href="#" rel="top" title="<?= t('var_medialist_move_top') ?>"></a>
		<a href="#" rel="up" title="<?= t('var_medialist_move_up') ?>"></a>
		<a href="#" rel="down" title="<?= t('var_medialist_move_down') ?>"></a>
		<a href="#" rel="bottom" title="<?= t('var_medialist_move_bottom') ?>" style="margin-right:2em"></a>
	</span>

	<span class="sly-icons edit">
		<a href="#" rel="open" title="<?= t('var_media_open') ?>"></a>
		<a href="#" rel="add" title="<?= t('var_media_new') ?>"></a>
		<a href="#" rel="delete" title="<?= t('var_media_remove') ?>"></a>
	</span>
</span>
