<?php
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

/**
 * @package redaxo4
 */

$resize   = sly_Service_Factory::getAddOnService()->isAvailable('image_resize');
$selected = $this->getCurrentCategory();

////////////////////////////////////////////////////////
// info and error messages

print $this->render('mediapool/notices.phtml');

////////////////////////////////////////////////////////
// list all files in the current category

$form = new sly_Form('index.php', 'POST', t('selected_category'), '', 'sly-form-mediapool-media');
$form->addHiddenValue('page', 'mediapool');
$form->addHiddenValue('func', 'batch');

// additional arguments

foreach ($this->args as $name => $value) {
	$form->addHiddenValue('args['.$name.']', $value);
}

$user    = sly_Util_User::getCurrentUser();
$isAdmin = $user->isAdmin() || $user->hasRight('media[0]');

ob_start();

?>
<table class="sly-table sly-mediapool-list" summary="">
	<caption><?php echo t('selected_media') ?></caption>
	<thead><tr>
		<th class="sly-col-icon sly-icon">&nbsp;</th>
		<th class="sly-col-thumbnail"><?php echo t('thumbnail') ?></th>
		<th class="sly-col-info"><?php echo t('file_info') ?> / <?php echo t('description') ?></th>
		<th class="sly-col-func"><?php echo t('functions') ?></th>
	</tr></thead>
	<?php

	// move and delete selected items

	if ($isAdmin) {
		$add_input = '';
		$select    = $this->getCategorySelect();

		if ($select->getValueCount() > 1) {
			$select->setAttribute('id', 'rex_move_file_dest_category');
			$select->setAttribute('onchange', '');

			$add_input =
				'<label for="rex_move_file_dest_category">'.t('selected_media').'</label>'.
				$select->render().
				'<input class="sly-form-submit-2 sly-button-changecat sly-form-submit" type="submit" name="move" value="'.t('move_to_category').'" />';
		}

		$add_input .= '<input class="sly-form-submit-2 sly-button-delete sly-form-submit" type="submit" name="delete" value="'.t('delete').'" />';

		?>
		<tfoot><tr>
			<td class="sly-col-sly-icon">
				<label class="sly-form-hidden-label" for="check_all"><?php echo t('select_all') ?></label>
				<input class="sly-form-checkbox sly-check-all" type="checkbox" id="check_all" data-target="selectedmedia[]" />
			</td>
			<td colspan="3" class="sly-col-footer"><?php echo $add_input ?></td>
		</tr></tfoot>
		<?php
	}

	print '<tbody>';

	$argUrl = $this->getArgumentString();

	foreach ($files as $file) {
		$id         = $file->getId();
		$filename   = $file->getFilename();
		$title      = $file->getTitle();
		$updatedate = sly_Util_String::formatDatetime($file->getUpdateDate());
		$updateuser = $file->getUpdateUser();

		// missing file?

		if (!$file->exists()) {
			$thumbnail = '<img src="assets/mime-error.png" width="44" height="38" alt="'.ht('file_not_found').'" />';
		}
		else {
			$file_ext = $file->getExtension();
			$icon_src = 'assets/mime-default.png';

			if ($this->isDocType($file)) {
				$icon_src = 'assets/mime-'.$file_ext.'.png';
			}

			$alt       = $file->getTitle();
			$thumbnail = '<img src="'.$icon_src.'" alt="'.sly_html($alt).'" title="'.sly_html($alt).'" />';

			if ($this->isImage($file)) {
				$width  = $file->getWidth();
				$height = $file->getHeight();

				list($width, $height) = $this->getDimensions($width, $height, 80, 70);

				$attrs = array(
					'alt'    => $alt,
					'title'  => $alt,
					'width'  => $width,
					'height' => $height
				);

				$encoded   = urlencode($filename);
				$timestamp = $file->getUpdateDate();

				if ($resize && $width) {
					$attrs['src'] = '../imageresize/'.$width.'w__'.$height.'h__'.$encoded.'?t='.$timestamp;
				}
				else {
					$attrs['src'] = '../data/mediapool/'.$encoded.'?t='.$timestamp;
				}

				$thumbnail = '<img '.sly_Util_HTML::buildAttributeString($attrs, array('alt')).' />';
			}
		}

		if ($title == '') $title = '['.t('no_title').']';

		$ilink  = 'index.php?page=mediapool_detail&amp;file_id='.$id.'&amp;rex_file_category='.$selected.$argUrl;
		$add_td = '<td>&nbsp;</td>';

		if ($isAdmin) {
			$add_td = '<td class="sly-col-icon sly-icon"><input class="sly-form-checkbox" type="checkbox" name="selectedmedia[]" value="'.$id.'" /></td>';
		}

		?>
		<tr>
			<?php echo $add_td ?>
			<td class="sly-col-thumbnail"><a href="<?php echo $ilink ?>"><?php echo $thumbnail ?></a></td>
			<td class="sly-col-info">
				<span><a href="<?php echo $ilink ?>"><?php echo sly_html($title) ?></a></span><br />
				<span><span class="rex-suffix"><?php echo sly_html($filename) ?> [<?php echo $file->getFormattedSize() ?>]</span></span><br />
				<span><?php echo $updatedate ?> | <?php echo sly_html($updateuser) ?></span>
			</td>
			<td class="sly-col-func"><?php

			$opener_link = $this->getOpenerLink($file);
			print sly_Core::dispatcher()->filter('SLY_MEDIA_LIST_FUNCTIONS', $opener_link, array('medium' => $file));

			?></td>
		</tr>
		<?php
	}

	if (empty($files)): ?>
		<tr>
			<td colspan="4" class="sly-col-empty"><?php echo t('no_media_found') ?></td>
		</tr>
	<?php endif ?>
	</tbody>
</table>
<?php

$container = new sly_Form_Container();
$container->setContent(ob_get_clean());

$form->add($container);
$form->setResetButton(null);
$form->setSubmitButton(null);
print $form->render();
