<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$callback = sly_request('callback', '');
$callback = preg_replace('#[^a-z0-9.]#i', '', $callback);

if ($callback):
?>
<script type="text/javascript">
$(function() {
	$('#sly-wrapper').delegate('a[href="#"]', 'click', function() {
		var self     = $(this);
		var filename = self.data('filename');
		var title    = self.data('title');
		var link     = 'data/mediapool/' + filename;
		var callback = window.opener['<?= $callback ?>'];
		var close    = true;

		// execute callback (media widget, WYMeditor, ...)
		if (typeof callback === 'function') {
			close = callback(filename, title, link);
		}

		// close the popup
		if (close) window.close();
	});

	var links = $('a[href!="#"]:visible'), len = links.length, i = 0;

	for (; i < len; ++i) {
		links[i].href = links[i].href += '&callback=<?= $callback ?>';
	}
});

function openPage(src) {
	window.opener.location.href = src;
	self.close();
}
</script>
<? endif ?>
