<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$callback = sly_request('callback', '');
$callback = preg_replace('#[^a-z0-9.]#i', '', $callback);
$advanced = sly_Util_User::getCurrentUser()->hasRight('advancedMode[]');

if ($callback) {
	ob_start();
?>
$(function() {
	$('#sly-wrapper').delegate('a[href="#"]', 'click', function() {
		var self     = $(this);
		var filename = self.data('filename');
		var title    = self.data('title');
		var link     = 'sally/data/mediapool/' + filename;
		var callback = window.opener['<?php echo $callback ?>'];
		var close    = true;
		var fullName = '';

		if (title.length === 0) {
			fullName = filename;
		}
		else {
			fullName = <?php echo $advanced ? "title + ' (' + filename + ')'" : 'title' ?>;
		}

		// execute callback (media widget, WYMeditor, ...)
		if (typeof callback === 'function') {
			close = callback(filename, fullName, title, link);
		}

		// close the popup
		if (close) window.close();
		return false;
	});

	var links = $('a[href!="#"]:visible'), len = links.length, i = 0;

	for (; i < len; ++i) {
		links[i].href = links[i].href += '&callback=<?php echo $callback ?>';
	}
});

function openPage(src) {
	window.opener.location.href = src;
	self.close();
}
<?php
	$javascript = ob_get_clean();
	sly_Core::getLayout()->addJavaScript($javascript);
}
?>
