<?php

foreach (array('warn', 'info') as $type) {
	if (empty($this->$type)) continue;

	if (is_array($this->$type)) {
		if (count($this->$type) > 1) {
			$message = implode('<br />', $this->$type);
		}
		else {
			$message = reset($this->$type);
		}
	}
	elseif (is_string($this->$type)) {
		$message = $this->$type;
	}

	print call_user_func_array(array('sly_Helper_Message', $type), array($message));
}
