<?php
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

////////////////////////////////////////////////////////
// print breadcrumb path

$base     = 'index.php?page=mediapool_structure&amp;cat_id=';
$textpath = '<li> : <a href="'.$base.'0">Start</a></li>';
$catID    = sly_request('cat_id', 'int');
$cat      = sly_Util_MediaCategory::findById($catID);

if ($cat === null) {
	$categories = sly_Util_MediaCategory::getRootCategories();
	$catID      = 0;
}
else {
	$categories = $cat->getChildren();
	$parents    = $cat->getParentTree();

	foreach ($parents as $parent) {
		$textpath .= '<li> : <a href="'.$base.$parent->getId().'">'.sly_html($parent->getName()).'</a></li>';
	}

	$textpath .= '<li> : <a href="'.$base.$catID.'">'.sly_html($cat->getName()).'</a></li>';
}

?>
<div class="sly-navi-path">
	<ul>
		<li><?= t('pool_kat_path') ?></li>
		<?= $textpath ?>
	</ul>
</div>
<?php

////////////////////////////////////////////////////////
// info and error messages

print $this->render('mediapool/notices.phtml');

////////////////////////////////////////////////////////
// start form if needed

$editID      = sly_request('edit_id', 'int');
$nativeFocus = sly_Helper_Modernizr::hasInput('autofocus');

if ($this->action == 'add' || $this->action == 'edit') {
	$addMode = $this->action == 'add';

	?>
	<form action="index.php" method="post">
		<fieldset>
			<input type="hidden" name="page" value="mediapool_structure" />
			<input type="hidden" name="cat_id" value="<?= $catID ?>" />
			<input type="hidden" name="func" value="<?= $this->action ?>" />
			<?php	if ($this->action): ?>
			<input type="hidden" name="edit_id" value="<?= $editID ?>" />
			<?php endif ?>

			<?php foreach ($this->args as $name => $value): ?>
			<input type="hidden" name="args[<?= $name ?>]" value="<?= sly_html($value) ?>" />
			<?php endforeach ?>
		</fieldset>
		<?php
}

?>
<table class="sly-table" id="sly-mediapool-structure" summary="<?= sly_html(t('pool_kat_summary')) ?>">
	<caption class="rex-hide"><?= sly_html(t('pool_kat_caption')) ?></caption>
	<thead><tr>
		<th class="sly-icon">
			<a class="rex-i-element rex-i-mediapool-category-add sly-sprite" href="<?= $base.$catID ?>&amp;func=add">
				<span class="rex-i-element-text"><?= t('pool_kat_create') ?></span>
			</a>
		</th>
		<th class="sly-small sly-col-b">ID</th>
		<th class="sly-col-c"><?= t('pool_kat_name') ?></th>
		<th class="sly-col-d" colspan="2"><?= t('pool_kat_function') ?></th>
	</tr></thead>
	<tbody><?php

	if ($this->action == 'add') {
		?>
		<tr class="active">
			<td class="sly-icon"><span class="rex-i-element rex-i-mediapool-category sly-sprite"><span class="rex-i-element-text"><?= t('pool_kat_create') ?></span></span></td>
			<td class="sly-small">-</td>
			<td>
				<label class="rex-form-hidden-label" for="rex-form-field-name"><?= t('pool_kat_name') ?></label>
				<input class="rex-form-text" type="text" size="10" id="rex-form-field-name" name="catname" value=""<?= $nativeFocus ? ' autofocus="autofocus"' : '' ?> />
			</td>
			<td class="sly-col-d" colspan="2">
				<input type="submit" class="rex-form-submit" value="<?= t('pool_kat_create') ?>" />
			</td>
		</tr>
		<?php
	}

	foreach ($categories as $cat) {
		$id = $cat->getId();

		if ($this->action == 'edit' && $editID == $id) {
			?>
			<tr class="active">
				<td class="sly-icon"><span class="rex-i-element rex-i-mediapool-category sly-sprite"><span class="rex-i-element-text"><?= sly_html($cat->getName())?></span></span></td>
				<td class="sly-small"><?= $id ?></td>
				<td>
					<label class="rex-form-hidden-label" for="rex-form-field-name"><?= t('pool_kat_name') ?></label>
					<input class="rex-form-text" type="text" id="rex-form-field-name" name="catname" value="<?= sly_html($cat->getName()) ?>"<?= $nativeFocus ? ' autofocus="autofocus"' : '' ?> />
				</td>
				<td class="sly-col-d" colspan="2">
					<input type="submit" class="rex-form-submit" value="<?= t('pool_kat_update') ?>" />
				</td>
			</tr>
			<?php
		}
		else {
			?>
			<tr>
				<td class="sly-icon"><a class="rex-i-element rex-i-mediapool-category sly-sprite" href="<?= $base.$id ?>"><span class="rex-i-element-text"><?= sly_html($cat->getName())?></span></a></td>
				<td class="sly-small"><?= $id ?></td>
				<td><a href="<?= $base.$id ?>"><?= sly_html($cat->getName()) ?></a></td>
				<td class="sly-col-e"><a href="<?= $base.$catID ?>&amp;func=edit&amp;edit_id=<?= $id ?>"><?= t('pool_kat_edit')?></a></td>
				<td class="sly-col-f"><a href="<?= $base.$catID ?>&amp;func=delete&amp;edit_id=<?= $id ?>" class="sly-delete"><?= t('pool_kat_delete') ?></a></td>
			</tr>
			<?php
		}
	}

	if (empty($categories) && $this->action !== 'add' && $this->action !== 'edit') {
		?>
		<tr>
			<td colspan="5" class="center"><?= t('pool_kat_empty') ?></td>
		</tr>
		<?php
	}

	?></tbody>
</table>

<?php

if ($this->action == 'add' || $this->action == 'edit') {
	print '</form>';

	if (!$nativeFocus) {
		?>
		<script type="text/javascript">
		document.getElementById('rex-form-field-name').focus();
		</script>
		<?php
	}
}
