<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

////////////////////////////////////////////////////////
// info and error messages

$this->render('mediapool/notices.phtml');

////////////////////////////////////////////////////////
// init form

$form = new sly_Form('index.php', 'POST', t('pool_sync_title'), '', 'rex-form-mediapool-sync');

$form->addHiddenValue('page', 'mediapool_sync');
$form->addHiddenValue('func', 'sync');

////////////////////////////////////////////////////////
// files title

$title = new sly_Form_Input_Text('ftitle', t('pool_file_title'));
$form->add($title);

////////////////////////////////////////////////////////
// category select box

$select = $this->getCategorySelect();
$select->setLabel(t('pool_file_category'));
$select->setAttribute('value', $this->getCurrentCategory());

$form->add($select);

////////////////////////////////////////////////////////
// setup buttons


$submit = $form->getSubmitButton();
$submit->setAttribute('name', 'save');
$submit->setAttribute('value', t('pool_sync_button'));

$form->setResetButton(null);
$form->setSubmitButton(null);

$buttons['submit'] = $submit;
$form->add(new sly_Form_ButtonBar($buttons));

////////////////////////////////////////////////////////
// start list of dangling files

$diffCount = count($diffFiles);
$label     = t('pool_sync_affected_files');
$title     = $label;

if ($diffCount) $title .= ' ('.$diffCount.')';

$form->beginFieldset($title);

if ($diffCount) {
	foreach($diffFiles as $key => $filename) {
		unset($diffFiles[$key]);
		$diffFiles[sly_Util_Medium::correctEncoding($key)] = $filename;
	}
	$form->add(new sly_Form_Select_Checkbox('sync_files', $label, array(), $diffFiles));
}
else {
	$form->add(new sly_Form_Text($label, t('pool_sync_no_diffs')));
}

////////////////////////////////////////////////////////
// and here we go!

$form = sly_Core::dispatcher()->filter('SLY_MEDIA_FORM_SYNC', $form);

if ($form instanceof sly_Form) {
	print $form->render();
}
