<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$selected   = $this->getCurrentCategory();
$dispatcher = sly_Core::dispatcher();

////////////////////////////////////////////////////////
// header

print $dispatcher->filter('PAGE_MEDIAPOOL_HEADER', '', array('category_id' => $selected));

////////////////////////////////////////////////////////
// category selection form

$select = $this->getCategorySelect();
$values = $select->getValues();

if (count($values) > 1) { // empty / 'no category' will hide the form
	$select->setAttribute('onchange', 'this.form.submit()');

	$form = new sly_Form('index.php', 'POST', t('pool_select_cat'), '', 'rex-form-mediapool-selectcategory');
	$form->addHiddenValue('page', 'mediapool');
	$form->addHiddenValue('callback', sly_request('callback', 'string'));

	// additional arguments

	foreach ($this->args as $name => $value) {
		$form->addHiddenValue('args['.$name.']', $value);
	}

	$form->add($select);
	$form->setResetButton(null);
	$form->setSubmitButton(null);

	$form = $dispatcher->filter('SLY_MEDIA_LIST_TOOLBAR', $form, array('category_id' => $selected));

	if ($form instanceof sly_Form) {
		print $form->render();
	}
}
