<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<title>SallyCMS .htaccess-Test</title>
	<script src="../../js/jquery.min.js" type="text/javascript"></script>
	<script src="../../js/standard.min.js" type="text/javascript"></script>
	<script type="text/javascript">
	jQuery(function($) {
		$('#security_warning').show();
		$('#nextstep').hide();
	});
	</script>
</head>
<body>
	<p>Diese Seite dürften Sie nie sehen.</p>
</body>
</html>
