<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $I18N;

$this->title($I18N->msg('setup_step5'));

print $I18N->msg('setup_051', '<h2 class="rex-hl2">', '</h2>');
print '<div class="rex-area-content">';
print $I18N->msg('setup_052', '<h3 class="rex-hl3">', '</h3>', ' class="rex-ul1"', '<a href="index.php">', '</a>');
print '<p class="rex-tx1">'.$I18N->msg('setup_053').'</p>';
print '</div>';


?>
