<?php

global $SLY, $I18N;

$this->title('SETUP: START');

$SLY['LANG'] = $this->lang;

print $I18N->msg('setup_005', '<h2 class="rex-hl2">', '</h2>');
print '<div class="rex-area-content">';

print $I18N->msg('setup_005_1', '<h3 class="rex-hl3">', '</h3>', ' class="rex-ul1"');
print '<div class="rex-area-scroll">';

$basedir = $SLY['FRONTEND_PATH'];
$license = '<p class="rex-tx1">'.nl2br(file_get_contents($basedir.'/_lizenz.txt')).'</p>';

print strpos($SLY['LANG'], 'utf') === false ? $license : utf8_encode($license);;

?>
	</div>
</div>

<div class="rex-area-footer">
	<p class="rex-algn-rght"><a href="index.php?page=setup&amp;func=fsperms&amp;lang=<?= urlencode($this->lang) ?>">&raquo; <?= $I18N->msg('setup_006') ?></a></p>
</div>

<? $this->footer(); ?>
