RELOGINDELAY: 2
START_PAGE: structure
EXTPERM: ["moveSlice", "copyContent", "copyArticle", "moveCategory", "publishCategory", "article2startpage"]
OBJECTPERM: ["clang", "media", "module"]
authorisation:
  pages:
    title: 'translate:pages'
    token:
      mediapool: 'translate:mediapool'
      addons: 'translate:addons'
  article:
    token:
      edit: 'translate:edit'
      move: 'translate:move'
      publish: 'translate:publish'
      editcontent: 'translate:editcontent'
    supers:
      read: ['edit', 'move', 'publish', 'edittype', 'editcontent']
      editcontent: ['edit']
