RELOGINDELAY: 2
START_PAGE: structure
PERM: ["mediapool"]
EXTPERM: ["moveSlice", "copyContent", "moveArticle", "copyArticle", "moveCategory", "publishArticle", "publishCategory", "article2startpage", "changearttype"]
EXTRAPERM: ["editContentOnly"]
OBJECTPERM: ["clang", "csw", "media", "module"]
