<?
global $REX;
include_once $REX['INCLUDE_PATH'].'/functions/function_rex_other.inc.php';
include_once $REX['INCLUDE_PATH'].'/functions/function_rex_addons.inc.php';
?>
<div class="rex-area rex-mab-10">
	<h3 class="rex-hl2">SallyCMS <?php echo $REX['VERSION'].'.'.$REX['SUBVERSION'].'.'.$REX['MINORVERSION'] ?></h3>

	<div class="rex-area-content">
		<p class="rex-tx1">
			<strong>Das webvariants-Team</strong>, <a href="mailto:info@webvariants.de">info@webvariants</a><br />
			Kernentwicklung<br />
			webvariants GbR, <a href="http://www.webvariants.de/" class="sly-blank">www.webvariants.de</a>
		</p>
	</div>
</div>

<div class="rex-area">
	<table class="rex-table sly-addonlist" summary="">
		<thead><tr>
			<th class="rex-icon">&nbsp;</th>
			<th><?= $I18N->msg('credits_name') ?></th>
			<th><?= $I18N->msg('credits_version') ?></th>
			<th><?= $I18N->msg('credits_author') ?></th>
			<th><?= $I18N->msg('credits_supportpage') ?></th>
		</tr></thead>
		<tbody>

		<?php
		
		$addons  = sly_Service_Factory::getService('AddOn');
		$plugins = sly_Service_Factory::getService('Plugin');

		foreach ($addons->getRegisteredAddons() as $addon) {
			$isActive    = $addons->isActivated($addon);
			$isInstalled = $addons->isInstalled($addon);
			$version     = $addons->getVersion($addon);
			$icon        = $addons->getIcon($addon);
			$author      = $addons->getAuthor($addon);
			$supportPage = $addons->getSupportPage($addon);
			
			$type = 'addon';
			include $REX['INCLUDE_PATH'].'/views/credits/row.phtml';
			
			if ($isActive) {
				$type = 'plugin';
				
				foreach ($plugins->getAvailablePlugins($addon) as $plugin) {
					$isActive    = $plugins->isActivated(array($addon, $plugin));
					$isInstalled = $plugins->isInstalled(array($addon, $plugin));
					$version     = $plugins->getVersion(array($addon, $plugin));
					$icon        = $plugins->getIcon(array($addon, $plugin));
					$author      = $plugins->getAuthor(array($addon, $plugin));
					$supportPage = $plugins->getSupportPage(array($addon, $plugin));
					
					include $REX['INCLUDE_PATH'].'/views/credits/row.phtml';
				}
			}
		}

		?>
		</tbody>
	</table>
</div>