<?

//$element = $type == 'addon' ? $addon : $plugin;
$class   = $isActive ? 'rex-clr-grn' : 'rex-clr-red';
$author  = $isActive ? sly_html($author) : $I18N->msg('credits_addon_inactive');

if ($isActive) $class .= ' sly-activated';
elseif ($isInstalled) $class .= ' sly-installed';
else $class .= ' sly-notinstalled';

if ($supportPage) {
	$supportPage = '<a href="http://'.sly_html($supportPage).'" class="sly-blank">'.sly_html($supportPage).'</a>';
}

if (!$icon) {
	$icon = 'media/'.$type.'.gif';
}

?>

<tr class="rex-<?= $type ?> sly-<?= $type ?> <?= $class ?>">
	<td class="sly-col-a rex-icon"><?= sly_Util_HTML::getSpriteLink('', $name, 'addon') ?></td>
	<td class="sly-col-b"><?= sly_html($name) ?> [<a href="index.php?page=addon&amp;subpage=help&amp;addonname=<?= urlencode($name) ?>">?</a>]</td>
	<td class="sly-col-c"><?= sly_html($version) ?></td>
	<td class="sly-col-d"><?= $author ?></td>
	<td class="sly-col-e"><?= $supportPage ?></td>
</tr>
