<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

if (!empty($this->warning)) print sly_Helper_Message::warn($this->warning);
if (!empty($this->info))    print sly_Helper_Message::info($this->info);

if ($this->func == 'add' || $this->func == 'edit'): ?>
<div class="sly-form">
	<form action="index.php" method="post">
		<input type="hidden" name="page" value="system_languages" />
		<input type="hidden" name="clang_id" value="<?php echo (int) $this->id ?>" />
		<input type="hidden" name="func" value="<?php echo $this->func ?>" />
	<?php endif ?>

	<?php

	$base = 'index.php?page=system_languages&func=';
	$link = sly_Util_HTML::getSpriteLink($base.'add', t('add_language'), 'language-add');

	$table = new sly_Table('languages');
	$table->addColumn(new sly_Table_Column($link, '', '', array('class' => 'sly-col-icon sly-icon')));
	$table->addColumn(new sly_Table_Column(t('name'), '', '', array('class' => 'sly-col-name')));
	$table->addColumn(new sly_Table_Column(t('locale'), '', '', array('class' => 'sly-col-locale')));
	$table->addColumn(new sly_Table_Column(t('function'), '', '', array('class' => 'sly-col-func')));

	$table->openBuffer();

	// Das Formular für neue Sprachen erscheint immer vor den anderen Daten.

	if ($this->func == 'add') {
		$name   = sly_post('clang_name', 'string');
		$locale = sly_post('clang_locale', 'string');

		?>
		<tr class="sly-active">
			<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', $name, 'language') ?></td>
			<td class="sly-col-name sly-has-input"><div><input class="sly-form-text" type="text" name="clang_name" value="<?php echo sly_html($name) ?>" autofocus="autofocus" required="required" placeholder="<?php echo ht('name') ?>" /></div></td>
			<td class="sly-col-locale sly-has-input"><div><input class="sly-form-text" type="text" name="clang_locale" value="<?php echo sly_html($locale) ?>" required="required" placeholder="<?php echo ht('locale') ?>" /></div></td>
			<td class="sly-col-func sly-has-input"><div><input type="submit" name="sly-submit" class="sly-form-submit" value="<?php echo t('add') ?>" /></div></td>
		</tr>
		<?php
	}

	foreach ($this->languages as $language) {
		print $this->render('system/languages_row.phtml', array(
			'clangID'     => $language->getId(),
			'clangName'   => $language->getName(),
			'clangLocale' => $language->getLocale()
		));
	}

	if ($this->func !== 'add' && $this->func !== 'edit' && empty($this->languages)) {
		?>
		<tr>
			<td colspan="4" class="sly-col-empty center"><?php echo t('no_languages_yet') ?></td>
		</tr>
		<?php
	}

	$table->closeBuffer();
	print $table->render();

	if ($this->func === 'add' || $this->func === 'edit'): ?>
	</form>
</div>
<?php endif ?>
