<?
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id  = $this->id ? ' id="'.sly_html($this->id).'"' : '';
$enc = $this->enctype ? ' enctype="'.sly_html($this->enctype).'"' : '';
?>

<div class="rex-addon-output-v2">
	<div class="rex-form sly-form">
		<form method="<?= strtolower($this->method) ?>" action="<?= sly_html($this->action) ?>"<?= $id.$enc ?>>
			<? if (!empty($this->hiddenValues)): ?>
			<div>
				<?php
				foreach ($this->hiddenValues as $name => $value) {
					$value['type'] = 'hidden';
					$value['name'] = $name;
					print '<input '.sly_Util_HTML::buildAttributeString($value).' />';
				}
				?>
			</div>
			<? endif ?>

			<?php
			$hasButtonBar = $this->submitButton || $this->resetButton || $this->applyButton || $this->deleteButton;

			if ($hasButtonBar) {
				$fieldset = end($this->fieldsets);
				if (!$fieldset) $fieldset = $this->beginFieldset($this->title);
				include $viewRoot.'buttons.phtml';
			}

			foreach ($this->fieldsets as $i => $fieldset) {
				$fieldset->render();
			}
			?>
		</form>
	</div>
</div>

<? if (!empty($this->focussedElement)): ?>
<script type="text/javascript">
// <[!CDATA[
jQuery('#<?= $this->focussedElement ?>').focus();
// ]]>
</script>
<? endif ?>