<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title><?= sly_html(trim($this->title)) ?></title>

	<?php
		rex_register_extension_point('PAGE_HEADER', '');
		if ($this->favIcon !== null) {
			print '<link href="'.$this->favIcon.'" rel="shortcut icon" type="image/x-icon" />';
		}
		$this->printHttpMetas();
		$this->printMetas();
		$this->printLinks();
		$this->printFeedFiles();
		$this->printCSSFiles();
		$this->printJavaScriptFiles();
		$this->printCSS();
		$this->printJavaScript();
	?>
</head>
<body <?= $this->printBodyAttrs() ?>>
