<?
$outerClass   = $element->getOuterClass();
$outerClass   = $outerClass ? ' class="'.$outerClass.'"' : '';
$formRowClass = $element->getFormRowClass();
$formRowClass = $formRowClass ? ' '.$formRowClass : '';
$help         = $element->getHelpText() ? '<span class="rex-form-notice">'.nl2br(sly_html($element->getHelpText())).'</span>' : '';
$isContainer  = $element->isContainer();
$label        = $element->getLabel();
$label        = empty($label) ? '&nbsp;' : sly_html($label.':');
$label        = preg_replace('#\*\*(.*?)\*\*#i', '<strong>$1</strong>', $label);
$label        = preg_replace('#__(.*?)__#i', '<em>$1</em>', $label);
$label        = preg_replace('#//(.*?)//#i', '<em>$1</em>', $label);

// Elemente einrücken

if (preg_match('#^( *)#', $label, $matches)) {
	$label = preg_replace('#^( *)#', str_repeat('&nbsp;', strlen($matches[1])), $label);
}

if ($isContainer) {
	print $element->render();
}
else {
	?>
	<div class="rex-form-row<?= $isLast ? ' last' : '' ?><?= $formRowClass ?>">
		<p<?= $outerClass ?>>
			<label for="<?= $element->getID() ?>"><?= $label ?></label>
			<?= $element->render() ?>
			<?= $help ?>
		</p>
	</div>
	<?
}
