<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Murphy Strikes Again!</title>
	<meta name="robots" content="none,noarchive">
	<style>
	h1, p { font-family: Calibri; }
	#horizon { background-color: transparent; position: absolute; top: 50%; left: 0px; width: 100%; margin-top: -100px; text-align: center; min-width: 700px; }
	#wrapper { margin: 0px auto; background-color: #fff; position: relative; text-align: left; width: 700px; height: 100px; }
	</style>
</head>
<body>
<div id="horizon">
	<div id="wrapper">
		<h1>Weeh! Seems like Murphy was right once again...</h1>
		<p>Es trat ein interner Fehler beim Verarbeiten Ihrer Anfrage auf. Bitte versuchen Sie es später noch einmal.</p>
	</div>
</div>
</body>
</html>
