<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<div class="sly-form-col-a sly-form-buttonbar">
	<?php
	foreach ($this->buttons as $button) {
		print $button->render();
	}
	?>
</div>
