<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<p class="rex-form-col-a rex-form-submit">
	<?php
	$additionalClass = '';

	foreach ($this->buttons as $button) {
		$button->addClass('rex-form-submit'.$additionalClass);
		$additionalClass = ' rex-form-submit-2';

		print $button->render();
	}
	?>
</p>
