<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$outerClass  = $element->getOuterClass();
$outerClass  = $outerClass ? ' class="'.$outerClass.'"' : '';
$help        = $element->getHelpText() ? '<span class="rex-form-notice">'.nl2br(sly_html($element->getHelpText())).'</span>' : '';
$isContainer = $element->isContainer();
$label       = $element->getLabel();
$label       = empty($label) ? '&nbsp;' : sly_html(rex_translate($label, null, false).':');

// Elemente einrücken

if (preg_match('#^( *)#', $label, $matches)) {
	$label = preg_replace('#^( *)#', str_repeat('&nbsp;', strlen($matches[1])), $label);
}

if ($isContainer) {
	print $element->render();
}
else {
	?>
	<div class="rex-form-row<?= $isLast ? ' last' : '' ?>">
		<p<?= $outerClass ?>>
			<label for="<?= $element->getID() ?>"><?= $label ?></label>
			<?= $element->render() ?>
			<?= $help ?>
		</p>
	</div>
	<?
}
