<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id    = $this->getID();
$class = empty($this->attributes['class']) ? '' : ' class="'.sly_html($this->attributes['class']).'"';

print '<span id="freeform-for-'.$id.'"'.$class.'>'.$this->content.'</span>';
