<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$usage  = function_exists('memory_get_peak_usage') ? memory_get_peak_usage() : memory_get_usage();
$usage  = sly_Util_String::formatFilesize($usage);
$usage .= ' in '.sly_Loader::getClassCount().' Klassen';

?>
	</div>
	<div id="sly-footer">
		<ul>
			<li class="rex-navi-first"><a href="#sly-navi-top">&#94;</a></li>
			<li><a href="http://www.webvariants.de/" class="sly-blank">webvariants.de</a></li>
			<li><a href="http://www.sallycms.de/" class="sly-blank">sallycms.de</a></li>
			<?php if ($REX['USER']): ?>
			<li><a href="index.php?page=credits"><?= t('credits') ?></a></li>
			<?php endif ?>
		</ul>
		<p class="sly-scripttime">
		<span title="<?= sly_html($usage) ?>"><?php print rex_showScriptTime() ?> Sek</span> |
		<?php print rex_formatter::format(time(), 'strftime', 'date') ?>
		</p>
	</div>
</div>
