<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

?>
			<!-- wegen dem bescheuerten rex_title hier ein schließendes div -->
			</div>
		</div>
	</div>


	<div id="rex-footer">
		<div id="rex-navi-footer">
			<ul>
				<li class="rex-navi-first">
					<a href="#rex-header">&#94;</a>
				</li>
				<li>
					<a href="http://www.webvariants.de/" class="sly-blank">webvariants.de</a>
				</li>
				<li>
					<a href="http://www.sallycms.de/" class="sly-blank">sallycms.de</a>
				</li>
				<? if ($REX['USER']): ?>
				<li>
					<a href="index.php?page=credits"><?= t('credits') ?></a>
				</li>
				<? endif ?>
			</ul>
			<p id="rex-scripttime"><!--DYN-->
			<?= rex_showScriptTime() ?> Sek |
			<?= sly_Util_String::formatFilesize(function_exists('memory_get_peak_usage') ? memory_get_peak_usage() : memory_get_usage()) ?> |
			<?= rex_formatter::format(time(), 'strftime', 'date'); ?>
			<!--/DYN--></p>
		</div>
	</div>
</div>
