<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $REX;
$config = sly_Core::config();

?>

<div id="sly-page">
	<div id="sly-navi-top" style="height: 88px;">
		<?php $this->renderView('views/layout/sally/navi_logout.phtml') ?>
	</div>
	<?php if ($REX['USER'] && $this->hasNavigation()): ?>
	<div id="sly-navi-main">
		<?php
		$this->renderView('views/layout/sally/navi_main.phtml');
		?>
	</div>
	<?php endif ?>

	<div id="rex-wrapper">
