<?php
/*
 * Copyright (c) 2009, webvariants GbR, http://www.webvariants.de
 *
 * Diese Datei steht unter der MIT-Lizenz. Der Lizenztext befindet sich in der
 * beiliegenden LICENSE Datei und unter:
 *
 * http://www.opensource.org/licenses/mit-license.php
 * http://de.wikipedia.org/wiki/MIT-Lizenz
 */

if ($this->func == 'edit') {
	$legend = $I18N->msg('module_edit').' [ID = '.$module->getId().']';
}
else {
	$legend = $I18N->msg('create_module');
}

// Formular vorbereiten

$form = new sly_Form('index.php', 'POST', $legend, '', 'module');
$form->addHiddenValue(sly_Controller_Base::PAGEPARAM,   'module');
$form->addHiddenValue(sly_Controller_Base::ACTIONPARAM, $this->func);
$form->addHiddenValue('save', 1);
$form->addHiddenValue('category_id', 0);

if ($this->func == 'edit') {
	$form->addHiddenValue('id', $module->getId());
}

// Felder erzeugen

$name   = new sly_Form_Input_Text('name', $I18N->msg('module_name'), $module ? $module->getName() : '');
$input  = new sly_Form_Textarea('input', $I18N->msg('input'), $module ? $module->getInput() : '');
$output = new sly_Form_Textarea('output', $I18N->msg('output'), $module ? $module->getOutput() : '');

$input->setAttribute('rows', 20);
$input->setAttribute('cols', 6);
$input->setAttribute('wrap', 'off');
$output->setAttribute('rows', 20);
$output->setAttribute('cols', 6);
$output->setAttribute('wrap', 'off');

$form->addElements(array($name, $input, $output));
$form->getSubmitButton()->setAttribute('value', $I18N->msg('save_module_and_quit'));

// Übernehmen-Button erzeugen

if ($this->func == 'edit') {
	$applyButton = new sly_Form_Input_Button('apply', 'gooon', $I18N->msg('save_module_and_continue'));
	$applyButton->setAttribute('type', 'submit');
	$form->setApplyButton($applyButton);
}

// Und raus damit!

$form->render();
