<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * Diese Datei steht unter der MIT-Lizenz. Der Lizenztext befindet sich in der
 * beiliegenden LICENSE Datei und unter:
 *
 * http://www.opensource.org/licenses/mit-license.php
 * http://de.wikipedia.org/wiki/MIT-Lizenz
 */

global $REX;

$base   = 'index.php?page=module&amp;func=';
$thIcon = '<a href="'.$base.'add"><img class="sly-icon sly-sprite sly-module-add" alt="" src="media/empty.png" title="'.$I18N->msg('create_module').'" /></a>';
$table  = new sly_Table('modules');

$table->addColumn(new sly_Table_Column($thIcon, '', '', array('class' => 'rex-icon')));
$table->addColumn(new sly_Table_Column('ID', '25px'));
$table->addColumn(new sly_Table_Column($I18N->msg('module_description')));
$table->addColumn(new sly_Table_Column($I18N->msg('module_functions'), '80px'));

$table->setIsEmpty(empty($modules));
$table->setEmptyNotice($I18N->msg('modules_not_found'));

$table->renderHeader(count($modules));

$tdIcon = '';

foreach ($modules as $module) {
	$id = (int) $module->getId();
	
	?>
	<tr>
		<td class="sly-col-a sly-icon">
			<a href="<?= $base ?>edit&amp;id=<?= $id ?>">
				<img src="media/empty.png" class="sly-icon sly-sprite sly-module" alt="" title="<?= sly_html($module->getName()) ?>" />
			</a>
		</td>
		<td class="sly-col-b sly-center"><?= $id ?></td>
		<td class="sly-col-c"><a href="<?= $base ?>edit&amp;id=<?= $id ?>"><?= sly_html($module->getName()) ?></a></td>
		<td class="sly-col-d"><a class="sly-action sly-delete" href="<?= $base ?>delete&amp;id=<?= $id ?>">Löschen</a></td>
	</tr>
	<?
}

$table->renderFooter();
