<?php
/*
 * Copyright (c) 2009, webvariants GbR, http://www.webvariants.de
 *
 * Diese Datei steht unter der MIT-Lizenz. Der Lizenztext befindet sich in der
 * beiliegenden LICENSE Datei und unter:
 *
 * http://www.opensource.org/licenses/mit-license.php
 * http://de.wikipedia.org/wiki/MIT-Lizenz
 */

global $REX;

$base   = 'index.php?page=module&amp;func=';
$thIcon = '<a href="'.$base.'add"><img class="sly-icon sly-sprite sly-module-add" alt="" src="media/empty.png" title="'.$I18N->msg('create_module').'" /></a>';
$table  = new sly_Table('modules');

$table->addColumn(new sly_Table_Column($thIcon, '', '', array('class' => 'rex-icon')));
$table->addColumn(new sly_Table_Column('ID', '25px'));
$table->addColumn(new sly_Table_Column($I18N->msg('module_description')));
$table->addColumn(new sly_Table_Column($I18N->msg('module_functions'), '80px'));

$table->setIsEmpty(empty($modules));
$table->setEmptyNotice($I18N->msg('modules_not_found'));

$table->renderHeader(count($modules));

$tdIcon = '';

foreach ($modules as $module) {
	$id = (int) $module->getId();
	
	?>
	<tr>
		<td class="sly-col-a sly-icon">
			<a href="<?= $base ?>edit&amp;id=<?= $id ?>">
				<img src="media/empty.png" class="sly-icon sly-sprite sly-module" alt="" title="<?= sly_html($module->getName()) ?>" />
			</a>
		</td>
		<td class="sly-col-b sly-center"><?= $id ?></td>
		<td class="sly-col-c"><a href="<?= $base ?>edit&amp;id=<?= $id ?>"><?= sly_html($module->getName()) ?></a></td>
		<td class="sly-col-d"><a class="sly-action sly-delete" href="<?= $base ?>delete&amp;id=<?= $id ?>">Löschen</a></td>
	</tr>
	<?
}

$table->renderFooter();

/*
$list = rex_list::factory('SELECT id, name FROM '.$REX['TABLE_PREFIX'].'module ORDER BY name');
$list->setCaption($I18N->msg('module_caption'));
$list->addTableAttribute('summary', $I18N->msg('module_summary'));
$list->addTableColumnGroup(array(40, 40, '*', 153));

$list->addColumn($thIcon, $tdIcon, 0, array('<th class="rex-icon">###VALUE###</th>','<td class="rex-icon">###VALUE###</td>'));
$list->setColumnParams($thIcon, array('func' => 'edit', 'modul_id' => '###id###'));

$list->setColumnLabel('id', 'ID');
$list->setColumnLayout('id', array('<th class="rex-small">###VALUE###</th>','<td class="rex-small">###VALUE###</td>'));

$list->setColumnLabel('name', $I18N->msg('module_description'));
$list->setColumnParams('name', array('func' => 'edit', 'modul_id' => '###id###'));

$list->addColumn($I18N->msg('module_functions'), $I18N->msg('delete_module'));
$list->setColumnParams($I18N->msg('module_functions'), array('func' => 'delete', 'modul_id' => '###id###'));
$list->addLinkAttribute($I18N->msg('module_functions'), 'onclick', 'return confirm(\''.$I18N->msg('delete').' ?\')');

$list->setNoRowsMessage($I18N->msg('modules_not_found'));

print $list->show();
*/
