<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

////////////////////////////////////////////////////////////
// Gebundene Actions anzeigen

$base   = 'index.php?page=module&amp;func=';
$thIcon = '<img class="sly-icon sly-sprite sly-module-action" alt="" src="media/empty.png" title="'.$I18N->msg('action').'" />';
$table  = new sly_Table('module_actions');

$table->addColumn(new sly_Table_Column($thIcon, '', '', array('class' => 'rex-icon')));
$table->addColumn(new sly_Table_Column($I18N->msg('action_name')));
$table->addColumn(new sly_Table_Column($I18N->msg('action_functions'), '80px'));
$table->renderHeader();

foreach ($actions as $primaryID => $action) {
	?>
	<tr>
		<td class="sly-col-a sly-icon">
			<a href="<?= $base ?>edit&amp;subpage=actions&amp;id=<?= $action->getId() ?>">
				<img src="media/empty.png" class="sly-icon sly-sprite sly-module-action" alt="" title="<?= sly_html($action->getName()) ?>" />
			</a>
		</td>
		<td class="sly-col-b"><a href="<?= $base ?>edit&amp;subpage=actions&amp;id=<?= $action->getId() ?>"><?= sly_html($action->getName()) ?></a></td>
		<td class="sly-col-c"><a class="sly-action sly-delete" href="<?= $base ?>delete_action&amp;id=<?= $module->getId() ?>&amp;pid=<?= $primaryID ?>">Löschen</a></td>
	</tr>
	<?
}

$table->renderFooter();

////////////////////////////////////////////////////////////
// Formular zum Hinzufügen einer neuen Action

$form = new sly_Form('index.php', 'POST', $I18N->msg('action_add'));
$form->addHiddenValue(sly_Controller_BASE::PAGEPARAM, 'module');
$form->addHiddenValue(sly_Controller_Base::ACTIONPARAM, 'add_action');
$form->addHiddenValue('save', 1);
$form->addHiddenValue('id', $module->getId());

$service = sly_Service_Factory::getService('Action');
$actions = array();

foreach ($service->find() as $action) {
	$actions[$action->getId()] = $action->getName();
}

$select = new sly_Form_Select_DropDown('action_id', $I18N->msg('action'), array(), $actions);
$select->setMultiple(false);

$form->add($select);
$form->render();
