<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

// Daten vorbereiten

$label     = t($this->func == 'edit' ? 'edit_user' : 'create_user');
$currentID = $REX['USER']->getId();
$PERM      = $REX['PERM'];
$EXTPERM   = empty($REX['EXTPERM']) ? array() : $REX['EXTPERM'];
$EXTRAPERM = empty($REX['EXTRAPERM']) ? array() : $REX['EXTRAPERM'];
$rights    = $user ? $user->getRightsAsArray() : array();

//////////////////////////////////////////////////////////////////
// start the form

$form = new sly_Form('index.php', 'POST', '');
$form->addHiddenValue('page', 'user');
$form->addHiddenValue('save', '1');
$form->addHiddenValue('func', $this->func);
$form->addHiddenValue('id', $user ? $user->getId() : 0);

//////////////////////////////////////////////////////////////////
// first row: login and password

if ($user) {
	$login = new sly_Form_Text(t('login_name'), $user->getLogin());
}
else {
	$login = new sly_Form_Input_Text('userlogin', t('login_name'), '');
}

$password = new sly_Form_Input_Text('userpsw', t('password'), '');

$form->beginFieldset($label, '', 2);
$form->addRow(array($login, $password));

//////////////////////////////////////////////////////////////////
// second row: name and description

$name        = new sly_Form_Input_Text('username', t('name'), $user ? $user->getName() : '');
$description = new sly_Form_Input_Text('userdesc', t('description'), $user ? $user->getDescription() : '');

$form->addRow(array($name, $description));

//////////////////////////////////////////////////////////////////
// third row: admin and status

$userAdmin  = new sly_Form_Input_Checkbox('is_admin', '', '1', t('user_admin'));
$userStatus = new sly_Form_Input_Checkbox('userstatus', '', '1', t('user_status'));

if ($user) {
	$userAdmin->setChecked($user->isAdmin());
	$userStatus->setChecked($user->getStatus());

	if ($currentID == $user->getId()) {
		$userAdmin->setDisabled(true);
		$userStatus->setDisabled(true);
	}
}

$form->addRow(array($userAdmin, $userStatus));

//////////////////////////////////////////////////////////////////
// fourth row: language access and backend locale

$languages = sly_Util_Language::findAll();
foreach ($languages as $id => $obj) $languages[$id] = $obj->getName();

$allowedCLangs = $user ? $user->getAllowedCLangs() : array();
$backendLocale = $user ? $user->getBackendLocale() : array();
$clangSelect   = new sly_Form_Select_DropDown('userperm_sprachen', t('user_lang_xs'), $allowedCLangs, $languages);
$localeSelect  = new sly_Form_Select_DropDown('userperm_mylang', t('backend_language'), $backendLocale, $this->getBackendLocales());

$localeSelect->setMultiple(false);
$clangSelect->setSize(3);
$clangSelect->setHelpText(t('ctrl'));

$form->addRow(array($clangSelect, $localeSelect));

//////////////////////////////////////////////////////////////////
// fifth row: backend startpage

$startPage       = $user ? $user->getStartPage() : array();
$startpageSelect = new sly_Form_Select_DropDown('userperm_startpage', t('startpage'), $startPage, $this->getPossibleStartpages());

$startpageSelect->setMultiple(false);
$form->addRow(array($startpageSelect));

//////////////////////////////////////////////////////////////////
// sixth row: permissions

sort($PERM);
sort($EXTPERM);
sort($EXTRAPERM);

$allPermSelect = new sly_Form_Select_DropDown('userperm_all', t('user_all'), $rights, array_combine($PERM, $PERM));
$extPermSelect = new sly_Form_Select_DropDown('userperm_ext', t('user_options'), $rights, array_combine($EXTPERM, $EXTPERM));

$allPermSelect->setSize(10);
$extPermSelect->setSize(10);
$allPermSelect->setHelpText(t('ctrl'));
$extPermSelect->setHelpText(t('ctrl'));

$form->addRow(array($allPermSelect, $extPermSelect));

//////////////////////////////////////////////////////////////////
// seventh row: cats checkboxes

$allCats      = new sly_Form_Input_Checkbox('userperm_cat_all', '', '1', t('all_categories'));
$allMediaCats = new sly_Form_Input_Checkbox('userperm_media_all', '', '1', t('all_mediafolder'));

if ($user) {
	$allCats->setChecked($user->hasRight('csw[0]'));
	$allMediaCats->setChecked($user->hasRight('media[0]'));
}

$form->addRow(array($allCats, $allMediaCats));

//////////////////////////////////////////////////////////////////
// eigth row: category selects

$allowedCategories      = $user ? $user->getAllowedCategories() : array();
$allowedMediaCategories = $user ? $user->getAllowedMediaCategories() : array();

$categorySelect = new sly_Form_Select_DropDown('userperm_cat', t('categories'), $allowedCategories, $this->getStructure());
$mediaCatSelect = new sly_Form_Select_DropDown('userperm_media', t('mediafolder'), $allowedMediaCategories, $this->getMediaStructure());

$categorySelect->setSize(20);
$mediaCatSelect->setSize(20);
$categorySelect->setHelpText(t('ctrl'));
$mediaCatSelect->setHelpText(t('ctrl'));

$form->addRow(array($categorySelect, $mediaCatSelect));

//////////////////////////////////////////////////////////////////
// nineth row: misc

$allowedModules  = $user ? $user->getAllowedModules() : array();
$moduleSelect    = new sly_Form_Select_DropDown('userperm_module', t('modules'), $allowedModules, $this->getModules());
$extraPermSelect = new sly_Form_Select_DropDown('userperm_extra', t('extras'), $rights, array_combine($EXTRAPERM, $EXTRAPERM));

$moduleSelect->setSize(10);
$extraPermSelect->setSize(10);
$moduleSelect->setHelpText(t('ctrl'));
$extraPermSelect->setHelpText(t('ctrl'));

$form->addRow(array($moduleSelect, $extraPermSelect));

//////////////////////////////////////////////////////////////////
// Finally, render it!

$form->setSubmitButton(null);
$form->setResetButton(null);

if ($user) {
	$form->addRow(array(
		new sly_Form_ButtonBar(array('submit' => new sly_Form_Input_Button('submit', 'submit', t('user_save')))),
		new sly_Form_ButtonBar(array('apply' => new sly_Form_Input_Button('submit', 'apply', t('user_apply'))))
	));
}
else {
	$form->addRow(array(
		new sly_Form_ButtonBar(array('submit' => new sly_Form_Input_Button('submit', 'submit', t('add_user'))))
	));
}

print $form->render();
