<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$base   = 'index.php?page=user&amp;func=';
$thIcon = '<a href="'.$base.'add"><img class="sly-icon sly-sprite sly-sprite-sly-user-add" alt="" src="assets/empty.png" title="'.t('create_user').'" /></a>';
$table  = new sly_Table('users');

$table->addColumn(new sly_Table_Column($thIcon, '', '', array('class' => 'sly-icon')));
$table->addColumn(new sly_Table_Column('ID', '25px'));
$table->addColumn(new sly_Table_Column(t('name')));
$table->addColumn(new sly_Table_Column(t('login')));
$table->addColumn(new sly_Table_Column(t('last_login'), '150px'));
$table->addColumn(new sly_Table_Column(t('user_delete'), '150px'));

$table->setIsEmpty(false);
$table->openBuffer();

$tdIcon    = '';
$user      = sly_Util_User::getCurrentUser();
$currentID = $user->getId();

foreach ($users as $user) {
	$id    = (int) $user->getId();
	$name  = $user->getName();
	$login = $user->getLogin();

	if (empty($name)) {
		$name = $login;
	}

	?>
	<tr>
		<td class="sly-col-a sly-icon">
			<a href="<?= $base ?>edit&amp;id=<?= $id ?>">
				<img src="assets/empty.png" class="sly-icon sly-sprite sly-sprite-sly-user" alt="" title="<?= sly_html($login) ?>" />
			</a>
		</td>
		<td class="sly-col-b sly-center"><?= $id ?></td>
		<td class="sly-col-c"><a href="<?= $base ?>edit&amp;id=<?= $id ?>"><?= sly_html($name) ?></a></td>
		<td class="sly-col-d"><?= sly_html($user->getLogin()) ?></td>
		<td class="sly-col-e"><?= sly_Util_String::formatDatetime($user->getLastTryDate()) ?></td>

		<? if ($id == $currentID): ?>
		<td class="sly-col-f"><span class="rex-strike"><?= t('user_delete') ?></span></td>
		<? else: ?>
		<td class="sly-col-f"><a class="sly-action sly-delete" href="<?= $base ?>delete&amp;id=<?= $id ?>"><?= t('user_delete') ?></a></td>
		<? endif ?>
	</tr>
	<?
}

$table->closeBuffer();
print $table->render(count($users));
