<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<div class="rex-area sly-credits">
	<h3 class="rex-hl2">SallyCMS <?php echo sly_Core::getVersion() ?></h3>

	<div class="rex-area-content">
		<p class="rex-tx1">
			<strong>Das webvariants-Team</strong>, <a href="mailto:info@webvariants.de">info@webvariants</a><br />
			Kernentwicklung<br />
			webvariants GbR, <a href="http://www.webvariants.de/" class="sly-blank">www.webvariants.de</a>
		</p>
	</div>
</div>

<table class="sly-table sly-addonlist" summary="<?php echo t('credits_caption') ?>">
	<caption><?php echo t('credits_caption') ?></caption>
	<thead><tr>
		<th class="sly-col-a sly-icon">&nbsp;</th>
		<th class="sly-col-b"><?php echo t('credits_name') ?></th>
		<th class="sly-col-c"><?php echo t('credits_version') ?></th>
		<th class="sly-col-d"><?php echo t('credits_author') ?></th>
		<th class="sly-col-e"><?php echo t('credits_supportpage') ?></th>
	</tr></thead>
	<tbody>

	<?php

	$addons  = sly_Service_Factory::getAddOnService();
	$plugins = sly_Service_Factory::getPluginService();

	foreach ($addons->getRegisteredAddons() as $addon) {
		$params['type']        = 'addon';
		$params['name']        = $addon;
		$params['isActive']    = $addons->isActivated($addon);
		$params['isInstalled'] = $addons->isInstalled($addon);
		$params['version']     = $addons->getVersion($addon);
		$params['author']      = $addons->getAuthor($addon);
		$params['supportPage'] = $addons->getSupportPageEx($addon);

		print $this->render('credits/row.phtml', $params);

		if ($addons->isAvailable($addon)) {
			$params['type'] = 'plugin';

			foreach ($plugins->getRegisteredPlugins($addon) as $plugin) {
				$params['type']        = 'plugin';
				$params['name']        = $plugin;
				$params['isActive']    = $plugins->isActivated(array($addon, $plugin));
				$params['isInstalled'] = $plugins->isInstalled(array($addon, $plugin));
				$params['version']     = $plugins->getVersion(array($addon, $plugin));
				$params['author']      = $plugins->getAuthor(array($addon, $plugin));
				$params['supportPage'] = $plugins->getSupportPageEx(array($addon, $plugin));

				print $this->render('credits/row.phtml', $params);
			}
		}
	}

	if (count($addons->getRegisteredAddons()) == 0) {
		?>
		<tr>
			<td class="rex-col-a center" colspan="5"><?php echo t('addon_empty_list') ?></td>
		</tr>
		<?php
	}

	?>
	</tbody>
</table>
