<?
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$author  = is_array($author) ? sly_Util_String::humanImplode($author) : $author;
$author  = !empty($author) ? sly_html($author) : 'N/A';
$version = !empty($version) ? sly_html($version) : 'N/A';

if ($isActive) $class = ' sly-activated';
elseif ($isInstalled) $class = ' sly-installed';
else $class = ' sly-not-installed';


?>

<tr class="sly-<?= $type ?> sly-<?= $type ?> <?= $class ?>">
	<?php if ($type == 'addon'): ?>
	<td class="sly-col-a sly-icon"><?= sly_Util_HTML::getSpriteLink('', $name, 'addon') ?></td>
	<?php else: ?>
	<td class="sly-col-a">&nbsp;</td>
	<?php endif ?>
	<td class="sly-col-b"><?= sly_html($name) ?> [<a href="index.php?page=addon_help&amp;addon=<?= urlencode($name) ?>">?</a>]</td>
	<td class="sly-col-c"><?= $version ?></td>
	<td class="sly-col-d"><?= $author ?></td>
	<td class="sly-col-e"><?= $supportPage ?></td>
</tr>
