<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $REX;

$base   = 'index.php?page=module&amp;subpage=actions&amp;func=';
$thIcon = '<a href="'.$base.'add"><img class="sly-icon sly-sprite sly-module-action-add" alt="" src="media/empty.png" title="'.$I18N->msg('action_create').'" /></a>';
$table  = new sly_Table('actions');

$table->addColumn(new sly_Table_Column($thIcon, '', '', array('class' => 'rex-icon')));
$table->addColumn(new sly_Table_Column('ID', '25px'));
$table->addColumn(new sly_Table_Column($I18N->msg('action_name')));
$table->addColumn(new sly_Table_Column('Preview-Event(s)', '120px'));
$table->addColumn(new sly_Table_Column('Presave-Event(s)', '120px'));
$table->addColumn(new sly_Table_Column('Postsave-Event(s)', '120px'));
$table->addColumn(new sly_Table_Column($I18N->msg('action_functions'), '80px'));

$table->setIsEmpty(empty($actions));
$table->setEmptyNotice($I18N->msg('actions_not_found'));

$table->renderHeader(count($actions));

$tdIcon  = '';
$modeMap = array(
	1 => '<span class="sly-mode-add">ADD</span>',
	2 => '<span class="sly-mode-edit">EDIT</span>',
	4 => '<span class="sly-mode-delete">DELETE</span>'
);

foreach ($actions as $action) {
	$id = (int) $action->getId();

	?>
	<tr>
		<td class="sly-col-a sly-icon">
			<a href="<?= $base ?>edit&amp;id=<?= $id ?>">
				<img src="media/empty.png" class="sly-icon sly-sprite sly-module-action" alt="" title="<?= sly_html($action->getName()) ?>" />
			</a>
		</td>
		<td class="sly-col-b sly-center"><?= $id ?></td>
		<td class="sly-col-c"><a href="<?= $base ?>edit&amp;id=<?= $id ?>"><?= sly_html($action->getName()) ?></a></td>
		<td class="sly-col-d sly-center"><?= implode(' ', $action->getMode('preview', $modeMap)) ?></td>
		<td class="sly-col-e sly-center"><?= implode(' ', $action->getMode('presave', $modeMap)) ?></td>
		<td class="sly-col-f sly-center"><?= implode(' ', $action->getMode('postsave', $modeMap)) ?></td>
		<td class="sly-col-g"><a class="sly-action sly-delete" href="<?= $base ?>delete&amp;id=<?= $id ?>">Löschen</a></td>
	</tr>
	<?
}

$table->renderFooter();
