<?php

global $REX, $I18N;

if ($REX['USER'] && !$REX['PAGE_NO_NAVI']) {
	$user_name = $REX['USER']->getValue('name') != '' ? $REX['USER']->getValue('name') : $REX['USER']->getValue('login');
	?>
	<ul class="rex-logout">
		<li class="rex-navi-first"><span><?= $I18N->msg('logged_in_as').' '.htmlspecialchars($user_name) ?></span></li>
		<li><a href="index.php?page=profile"><?= $I18N->msg('profile_title') ?></a></li>
		<li><a href="index.php?rex_logout=1"><?= $I18N->msg('logout') ?></a></li>
		<li><a href="../">zur Website</a></li>
	</ul>
	<?php
}
elseif (!$REX['PAGE_NO_NAVI']) {
	echo '<p class="rex-logout">'.$I18N->msg('logged_out').'</p>';
}
else {
	echo '<p class="rex-logout">&nbsp;</p>';
}
