<?php
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

?>
<div id="rex-linkmap">
	<div class="rex-area-col-2">
		<div class="rex-area-col-a">
			<h3 class="rex-hl2"><?= t('lmap_categories') ?></h3>
			<div class="rex-area-content">
			<?php
			$roots = sly_Util_Category::getRootCategories();
			print $this->tree($roots);
			?>
			</div>
		</div>

		<div class="rex-area-col-b">
			<h3 class="rex-hl2"><?= t('lmap_articles') ?></h3>
			<div class="rex-area-content articlelist">
				<ul>
				<?php

				$category_id = $this->getGlobals('category_id', 0);
				$isRoot      = $category_id == 0;
				$category    = sly_Util_Category::findById($category_id);

				if ($isRoot) $articles = sly_Util_Article::getRootArticles();
				elseif ($category) $articles = $category->getArticles();
				else $articles = array();

				foreach ($articles as $article) {
					if ($article->isStartArticle() && $article->getId() != $category_id) {
						continue;
					}

					$label    = $this->formatLabel($article);
					$selected = $article->getId() == $this->getGlobals('category_id', 0);
					$liAttr   = $selected ? ' id="rex-linkmap-active"' : '';
					$class    = $article->isOnline() ? 'rex-online' : 'rex-offine';
					$linkAttr = 'class="'.$class.'" data-id="'.$article->getId().'" data-name="'.sly_html($article->getName()).'"';

					print '<li '.$liAttr.'><a href="#" '.$linkAttr.'>'.sly_html($label).'</a></li>';
				}
				?>
				</ul>
			</div>
		</div>
	</div>
</div>
