<div class="sly-content rex-addon-output-v2">
	<?

	// Meldungen ausgeben

	if (!empty($info))    print rex_info($info);
	if (!empty($warning)) print rex_warning($warning);

	// Intro-Text

	print '<p>'.$I18N->msg('im_export_intro_import').'</p>';

	// Formular erzeugen

	$baseDir = $REX['INCLUDE_PATH'].'/addons/import_export/backup';
	$dumps   = sly_A1_Helper::getDatabaseDumps($baseDir);
	$tars    = sly_A1_Helper::getFileArchives($baseDir);
	
	$table = new sly_Table('dumps');
	$table->addColumn(new sly_Table_Column('<img src="images/import_export/database.png" alt="" />', '', '', array('class' => 'rex-icon')));
	$table->addColumn(new sly_Table_Column('Datei', 'auto'));
	$table->addColumn(new sly_Table_Column('Optionen', 'auto', '', array('colspan' => 2)));
	$table->addColumn(new sly_Table_Column('Datum', '150px'));
	$table->addColumn(new sly_Table_Column('Größe', '80px'));
	$table->setIsEmpty(empty($dumps));
	$table->setEmptyNotice('Es sind keine Datenbank-Backups vorhanden.');
	$table->renderHeader();
	
	foreach ($dumps as $dump) {
		$info = sly_A1_Helper::getFileInfo($baseDir.'/'.$dump);
		if (!$info['exists']) continue;
		
		$baseURL = 'index.php?page=import_export&amp;subpage=import&amp;file='.urlencode($dump).'&amp;function=';
		
		?>
		<tr>
			<td class="rex-col-a rex-icon"><img src="images/import_export/database.png" alt="" /></td>
			<td class="rex-col-b">
				<a href="<?= $baseURL ?>download" title="<?= sly_html($dump) ?>"><?= sly_html($info['filename']) ?></a>
				<? if (!empty($info['description'])): ?>
				<span>(<?= sly_html($info['description']) ?>)</span>
				<? endif ?>
			</td>
			<td class="rex-col-c"><a href="<?= $baseURL ?>dbimport">einspielen</a></td>
			<td class="rex-col-d"><a href="<?= $baseURL ?>delete">löschen</a></td>
			<td class="rex-col-e"><?= strftime('%d.%m.%Y um %H:%M Uhr', $info['date']) ?></td>
			<td class="rex-col-f"><?= sly_String::formatFilesize($info['size']) ?></td>
		</tr>
		<?
	}
	
	$table->renderFooter();

	?>
</div>
