<?php
if ($article->isStartPage())
	$sprite = 'article-startpage';
else
	$sprite = 'article';

$base_url = 'index.php?page=content&article_id=' . $article->getId() . '&clang=' . $this->clangId;
$edit_url = 'index.php?page=structure&amp;category_id=' . $article->getParentId() . '&amp;clang=' . $this->clangId . '&amp;edit_id=' . $article->getId();
$status = $statusTypes[$article->getStatus()][0];
$status_class = $statusTypes[$article->getStatus()][1];
if ($this->canPublishCategory($article->getId()) && $this->categoryId != $article->getId()) {
	$status = '<a href="' . $edit_url . '&amp;func=editStatusArticle" class="' . $status_class . '">' . $status . '</a>';
}else {
	$status_class .= ' rex-strike';
	$status = '<span class="' . $status_class . '">' . $status . '</span>';
}
?>
<tr>
	<td class="sly-icon"><?= sly_Util_HTML::getSpriteLink($base_url, $article->getName(), $sprite) ?></td>
	<?= $advancedMode ? '<td class="rex-small">' . sly_html($category->getId()) . '</td>' : '' ?>
	<td><a href="<?= sly_html($base_url) ?>"><?= sly_html($article->getName()) ?></a></td>
	<td><?= sly_html($article->getPrior()) ?></td>
	<td><?= rex_formatter::format($article->getCreateDate(), 'strftime', 'date') ?></td>
	<td>
		<a href="<?= $edit_url ?>&amp;func=editArticle"><?= t('change') ?></a>&nbsp;
		<?php
		if ($canEdit && $this->categoryId != $article->getId()) {
			echo '<a href="' . $edit_url . '&amp;func=deleteArticle" onclick="return confirm(\'' . t('delete') . ' ?\')">' . t('delete') . '</a>';
		} else {
			echo '<span class="rex-strike">' . t('delete') . '</span>';
		}
		?>
		&nbsp;<?= $status ?>
	</td>
</tr>