<?
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id = $this->javascriptID;
?>
<input type="text" style="width:50%" size="30" name="<?= wv_html($this->attributes['id']) ?>" value="<?= wv_html($this->attributes['value']) ?>" class="<?= wv_html($this->attributes['class']) ?>" id="REX_MEDIA_<?= $id ?>" readonly="readonly" />

<span class="rex-wdgt-icons">
  	<a href="#" onclick="openREXMedia(<?= $id ?>, ''); return false;"><img src="media/file_open.gif" width="16" height="16" title="Medium auswählen" alt="Medium auswählen" /></a>
  	<a href="#" onclick="addREXMedia(<?= $id ?>); return false;"><img src="media/file_add.gif" width="16" height="16" title="Medium hinzufügen" alt="Medium hinzufügen" /></a>
  	<a href="#" onclick="deleteREXMedia(<?= $id ?>); return false;"><img src="media/file_del.gif" width="16" height="16" title="Medium entfernen" alt="Medium entfernen" /></a>
</span>
