<?
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id = $this->javascriptID;
?>
<input type="hidden" name="<?= $this->attributes['id'] ?>" id="REX_MEDIALIST_<?= $id ?>" value="<?= wv_html(implode(',', (array)$this->attributes['value'])) ?>" />
<select name="MEDIALIST_SELECT[<?= $id ?>]" id="REX_MEDIALIST_SELECT_<?= $id ?>" size="8" class="<?= wv_html($this->attributes['class']) ?>">
<?
	$files = empty($this->attributes['value']) ? array() : $this->attributes['value'];
	$files = array_filter($files);

	foreach ($files as $file) {
		?><option value="<?= wv_html($file) ?>"><?= wv_html($file) ?></option><?
	}
?>
</select>

<span class="rex-notice">
	<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'top'); return false;"><img src="media/file_top.gif" width="16" height="16" title="Ganz Hoch schieben" alt="Ganz Hoch schieben" /></a>
	<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'up'); return false;"><img src="media/file_up.gif" width="16" height="16" title="Hoch schieben" alt="Hoch schieben" /></a>
	<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'down'); return false;"><img src="media/file_down.gif" width="16" height="16" title="Runter schieben" alt="Runter schieben" /></a>
	<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'bottom'); return false;" style="margin-right:2em"><img src="media/file_bottom.gif" width="16" height="16" title="Ganz runter schieben" alt="Ganz runter schieben" /></a>
	<a href="#" onclick="openREXMedialist(<?= $id ?>); return false;"><img src="media/file_open.gif" width="16" height="16" title="Medium öffnen" alt="Medium öffnen" /></a>
	<a href="#" onclick="addREXMedialist(<?= $id ?>); return false;"><img src="media/file_add.gif" width="16" height="16" title="Medium hinzufügen" alt="Medium hinzufügen" /></a>
	<a href="#" onclick="deleteREXMedialist(<?= $id ?>); return false;"><img src="media/file_del.gif" width="16" height="16" title="Medium entfernen" alt="Medium entfernen" /></a>
</span>
