<?
$outerClass  = $element->getOuterClass($this->redaxo);
$outerClass  = $outerClass ? ' class="'.$outerClass.'"' : '';
$help        = $element->getHelpText() ? '<span class="rex-form-notice">'.nl2br(wv_html($element->getHelpText())).'</span>' : '';
$isContainer = $element->isContainer();
$label       = $element->getLabel();
$label       = empty($label) ? '&nbsp;' : wv_html($label.':');

// Elemente einrücken

if (preg_match('#^( *)#', $label, $matches)) {
	$label = preg_replace('#^( *)#', str_repeat('&nbsp;', strlen($matches[1])), $label);
}

if ($isContainer) {
	print $element->render($this->redaxo);
}
else {
	?>
	<div class="rex-form-row<?= $isLast ? ' last' : '' ?>">
		<p<?= $outerClass ?>>
			<label for="<?= $element->getID() ?>"><?= $label ?></label>
			<?= $element->render($this->redaxo) ?>
			<?= $help ?>
		</p>
	</div>
	<?
}
