<?
if (!empty($this->hiddenValues)) print '<div>';
foreach ($this->hiddenValues as $name => $value) {
	print '<input type="hidden" name="'.wv_html($name).'" value="'.wv_html($value['value']).'"';
	if (!empty($value['id'])) print ' id="'.wv_html($value['id']).'"';
	print ' />'.PHP_EOL;
}
if (!empty($this->hiddenValues)) print '</div>';

$elementCount = count($this->elements);

foreach ($this->elements as $x => $element) {
	$isLast = $x-1 == $elementCount;
	include 'element.phtml';
}
