<? $id = $this->javascriptID; ?>

<span class="sly-widget sly-mediabutton">
	<input type="text" style="width:50%" size="30" name="<?= sly_html($this->attributes['id']) ?>" value="<?= sly_html($this->attributes['value']) ?>" class="<?= sly_html($this->attributes['class']) ?>" id="REX_MEDIA_<?= $id ?>" readonly="readonly" />

	<span class="sly-icons">
		<a href="#" onclick="openREXMedia(<?= $id ?>, ''); return false;"><img src="media/file_open.gif" title="Medium auswählen" alt="Medium auswählen" /></a>
		<a href="#" onclick="addREXMedia(<?= $id ?>); return false;"><img src="media/file_add.gif" title="Medium hinzufügen" alt="Medium hinzufügen" /></a>
		<a href="#" onclick="deleteREXMedia(<?= $id ?>); return false;"><img src="media/file_del.gif" title="Medium entfernen" alt="Medium entfernen" /></a>
	</span>
</span>
