ADDON:
  install:
    be_search: 0
    be_style: 0
    fscache: 0
    image_resize: 0
    rbac: 0
  status:
    be_search: 0
    be_style: 0
    fscache: 0
    image_resize: 0
    rbac: 0
  plugins:
    be_style:
      install:
        agk_skin: 1
      status:
        agk_skin: 1
