SETUP: true
SERVER: sallycms.de
SERVERNAME: webvariants-Projekt
ERROR_EMAIL: webadmin@webvariants.de
INSTNAME: sly20100511212501
MYSQL_VERSION: null
START_ARTICLE_ID: 1
NOTFOUND_ARTICLE_ID: 1
START_CLANG_ID: 0
DEFAULT_TEMPLATE_ID: 0
LANG: de_de_utf8
USE_MD5: never
DATABASE:
  DRIVER: mysql
  HOST: localhost
  LOGIN: develop
  PASSWORD: develop
  NAME: webvariants_sally_base
  PERSISTENT: false
  TABLE_PREFIX: sly_
PERM: [mediapool]
EXTPERM: [advancedMode, moveSlice, copyContent, moveArticle, copyArticle, moveCategory, publishArticle, publishCategory, article2startpage]
EXTRAPERM: [editContentOnly]
ADDON:
  be_style:
    install: true
    status: true
    plugins: {agk_skin: {install: true, status: true}}
