<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

if (!empty($info))    print rex_info($info);
if (!empty($warning)) print rex_warning($warning);

?>
<table class="rex-table">
	<caption>Liste der verfügbaren AddOns</caption>
	<colgroup>
		<col width="40" />
		<col width="*"/>
		<col width="130" />
		<col width="130" />
		<col width="130" />
		<col width="153" />
	</colgroup>
		<thead>
			<tr>
				<th class="rex-icon rex-col-a">&nbsp;</th>
				<th class="rex-col-b"><?= $I18N->msg('addon_hname') ?></th>
				<th class="rex-col-c"><?= $I18N->msg('addon_hinstall') ?></th>
				<th class="rex-col-d"><?= $I18N->msg('addon_hactive') ?></th>
				<th class="rex-col-e"><?= $I18N->msg('addon_hdelete') ?></th>
			</tr>
		</thead>
	<tbody>

	<?php

	$addonList = $addons->getRegisteredAddOns();

	foreach ($addonList as $addon) {
		$base       = 'index.php?page=addon&amp;addon='.urlencode($addon).'&amp;func=';
		$registeredPlugins = $plugins->getRegisteredPlugins($addon);
		$availablePlugins  = $plugins->getAvailablePlugins($addon);

		if ($addons->isInstalled($addon)) {
			$install = $I18N->msg('addon_yes').' - <a href="'.$base.'install">'.$I18N->msg('addon_reinstall').'</a>';

			if (!empty($availablePlugins)) {
				$uninstall = $I18N->msg('plugin_plugins_installed');
			}
			else {
				$uninstall = '<a href="'.$base.'uninstall" onclick="return confirm(\''.sly_html($I18N->msg('addon_uninstall_question', $addon)).'\');">'.$I18N->msg('addon_uninstall').'</a>';
			}
		}
		else {
			$install   = $I18N->msg('addon_no').' - <a href="'.$base.'install">'.$I18N->msg('addon_install').'</a>';
			$uninstall = $I18N->msg('addon_notinstalled');
		}

		if ($addons->isActivated($addon)) {
			$status = $I18N->msg('addon_yes').' - <a href="'.$base.'deactivate">'.$I18N->msg('addon_deactivate').'</a>';
		}
		elseif ($addons->isInstalled($addon)) {
			$status = $I18N->msg('addon_no').' - <a href="'.$base.'activate">'.$I18N->msg('addon_activate').'</a>';
		}
		else {
			$status = $I18N->msg('addon_notinstalled');
		}

		?>
		<tr class="rex-addon">
			<td class="rex-icon rex-col-a"><?= sly_Util_HTML::getSpriteLink('', $addon, 'addon') ?></td>
			<td class="rex-col-b"><?= sly_html($addon) ?> [<a href="index.php?page=addon&amp;subpage=help&amp;addon=<?= urlencode($addon) ?>">?</a>]</td>
			<td class="rex-col-c"><?= $install ?></td>
			<td class="rex-col-d"><?= $status ?></td>
			<td class="rex-col-e"><?= $uninstall ?></td>
		</tr>
		<?php

		if ($addons->isAvailable($addon)) {
			foreach ($registeredPlugins as $plugin) {
				$comp = array($addon, $plugin);
				$base = 'index.php?page=addon&amp;addon='.urlencode($addon).'&amp;plugin='.urlencode($plugin).'&amp;func=';

				if ($plugins->isInstalled($comp)) {
					$install   = $I18N->msg('addon_yes').' - <a href="'.$base.'install">'.$I18N->msg('addon_reinstall').'</a>';
					$uninstall = '<a href="'. $base .'uninstall" onclick="return confirm(\''.htmlspecialchars($I18N->msg('plugin_uninstall_question', $addon)).'\');">'.$I18N->msg('addon_uninstall').'</a>';
				}
				else {
					$install   = $I18N->msg('addon_no').' - <a href="'.$base.'install">'.$I18N->msg('addon_install').'</a>';
					$uninstall = $I18N->msg('addon_notinstalled');
				}

				if ($plugins->isActivated($comp)) {
					$status = $I18N->msg('addon_yes').' - <a href="'.$base.'deactivate">'.$I18N->msg('addon_deactivate').'</a>';
				}
				elseif ($plugins->isInstalled($comp)) {
					$status = $I18N->msg('addon_no').' - <a href="'.$base.'activate">'.$I18N->msg('addon_activate').'</a>';
				}
				else {
					$status = $I18N->msg('addon_notinstalled');
				}

				?>
				<tr class="rex-plugin">
					<td class="rex-icon rex-col-a"><span class="rex-i-element rex-i-plugin"><span class="rex-i-element-text"><?= sly_html($plugin) ?></span></span></td>
					<td class="rex-col-b"><?= sly_html($plugin) ?> [<a href="index.php?page=addon&amp;subpage=help&amp;addon=<?= urlencode($addon) ?>&amp;plugin=<?= urlencode($plugin) ?>">?</a>]</td>
					<td class="rex-col-c"><?= $install ?></td>
					<td class="rex-col-d"><?= $status ?></td>
					<td class="rex-col-e"><?= $uninstall ?></td>
				</tr>
				<?php
			}
		}
	}

	if (empty($addonList)) {
		?>
		<tr>
			<td class="rex-col-a center" colspan="6"><?= $I18N->msg('addon_empty_list') ?></td>
		</tr>
		<?php
	}

	?>
	</tbody>
</table>
