<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$form = new sly_Form('index.php', 'POST', '');
$form->addHiddenValue('page', 'profile');
$form->addHiddenValue('func', 'update');

$login        = new sly_Form_Text(t('login_name'), $user->getLogin());
$password     = new sly_Form_Input_Text('userpsw', t('new_password'), '');
$username     = new sly_Form_Input_Text('username', t('name'), $user->getName());
$userdesc     = new sly_Form_Input_Text('userdesc', t('description'), $user->getDescription());
$localeSelect = new sly_Form_Select_DropDown('userperm_mylang', t('backend_language'), $user->getBackendLocale(), $this->getBackendLocales(), 'userperm-mylang');

$password->setHelpText(t('psw_encrypted'));
$localeSelect->setMultiple(false);

$form->beginFieldset(t('profile_myprofile'), '', 2);
$form->addRow(array($login, $password));
$form->addRow(array($username, $userdesc));
$form->addRow(array($localeSelect));

$form->getSubmitButton()->setAttribute('value', t('profile_save'));
$form->setResetButton(null);
$form->render();
