<?
$name     = $this->getAttribute('name');
$selected = $this->attributes['value'];

if ($this->getAttribute('multiple') == 'multiple') {
	$this->setAttribute('name', $name.'[]');
}

$this->addClass('rex-form-select');

print '<select '.$this->getAttributeString('value').'>';

foreach ($this->values as $key => $value) {
	$sel = (is_array($selected) && in_array($key, $selected)) || (!is_array($selected) && $key == $selected) ? ' selected="selected"' : '';
	print '<option value="'.sly_html($key).'"'.$sel.'>'.sly_html($value).'</option>';
}

print '</select>';
