<?
$tableID        = $this->id;
$currentPage    = abs(sly_get('p_'.$tableID, 'int'));
$hasPager       = $this->hasPager();
$hasSearch      = $this->hasSearch();
$hasDragAndDrop = $this->hasDragAndDrop();

$this->surroundingHTML = '';
ob_start();

$style = 'margin-bottom:1em;font-size:11px;line-height:20px';

if (!self::isDragAndDropMode() && $hasPager) {
	$pager = new sly_Pager($currentPage, $this->totalElements, self::$perPage);
	$pager = $pager->getHTMLString($_GET, 'p_'.$tableID);
	
	print '<p style="'.$style.';float:left">Seiten: '.$pager.'</p>';
}

if ($this->enableDragAndDrop && ($hasSearch || $hasPager)) {
	$params = $_GET;

	unset($params['p_'.$tableID]);
	unset($params['q_'.$tableID]);
	
	if (self::isDragAndDropMode()) {
		unset($params['tableswitch']);
		$params = http_build_query($params, '', '&amp;');
		print '<p style="'.$style.';float:right;margin-left:20px"><a href="index.php?'.$params.'">Sortiermodus beenden</a></p>';
	}
	else {
		$params['tableswitch'] = 'dodraganddrop';
		$params = http_build_query($params, '', '&amp;');
		print '<p style="'.$style.';float:right;margin-left:20px"><a href="index.php?'.$params.'">Tabelle sortieren</a></p>';
	}
}

if (!self::isDragAndDropMode() && $hasSearch) {
	$key   = 'q_'.$tableID;
	$query = wv_get($key, 'string');
	
	print '<form method="get" action="index.php">';
	print '<p style="margin-bottom:1em;font-size:11px;float:right;line-height:20px">Filter: ';
	
	foreach ($_GET as $name => $value) {
		if ($name != 'p_'.$this->id && $name != $key && is_scalar($value)) {
			print '<input type="hidden" name="'.wv_html($name).'" value="'.wv_html($value).'" />';
		}
	}
	
	print '<input type="text" name="'.$key.'" value="'.wv_html($query).'" class="filter_input_'.$this->id.'" style="width:150px" />';
	
	print '</p>';
	print '</form>';
}

$this->surroundingHTML = ob_get_clean();
print $this->surroundingHTML;

?>

<table id="<?= $this->id ?>" class="rex-table" style="margin-bottom:1em;clear:both">
	<thead>
		<tr class="nodrop nodrag">
			<?
			foreach ($this->columns as $col) {
				$col->render($this);
			}
			?>
		</tr>
	</thead>
	<tbody>
	