<?php

global $I18N;

$popups_arr = array('linkmap', 'mediapool');
$config     = sly_Core::config();
$title      = array($config->get('SERVERNAME'), $this->title, $this->subtitle);
$title      = array_map('sly_html', array_filter($title));

$body_id  = str_replace('_', '-', $config->get('PAGE'));
$bodyAttr = 'id="rex-page-'.$body_id.'"';

if (in_array($body_id, $popups_arr)) {
	$bodyAttr .= ' class="rex-popup"';
}

if ($config->get('PAGE_NO_NAVI')) {
	$bodyAttr .= ' onunload="closeAll()"';
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $I18N->msg('htmllang') ?>" lang="<?= $I18N->msg('htmllang') ?>">
<head>
	<? $this->renderView('views/_view/xhtml/head.phtml') ?>
</head>
<body <?= $bodyAttr ?>>
	<div id="rex-website">
		<div id="rex-header">
			<p class="rex-header-top"><a href="../" onclick="window.open(this.href);"><?= sly_html($config->get('SERVERNAME')) ?></a></p>
		</div>

		<div id="rex-navi-logout">
			<? $this->renderView('views/_view/xhtml/navi_logout.phtml') ?>
		</div>

		<div id="rex-navi-main">
			<?
			if ($config->get('USER') && !$config->get('PAGE_NO_NAVI')) {
				$this->renderView('views/_view/xhtml/navi_main.phtml');
			}
			?>
		</div>

		<div id="rex-wrapper">
			<div id="rex-wrapper2">
				<?= $this->content ?>
			</div>
		</div>
	</div>

	<div id="rex-footer">
		<div id="rex-navi-footer">
			<ul>
				<li class="rex-navi-first"><a href="#rex-header">&#94;</a></li>
				<li><a href="http://www.webvariants.de/" class="sly-blank">webvariants.de</a></li>
				<li><a href="http://www.sallycms.de/" class="sly-blank">sallycms.de</a></li>
				<? if ($config->get('USER')): ?>
				<li><a href="index.php?page=credits"><?= $I18N->msg('credits') ?></a></li>
				<? endif ?>
			</ul>
			<p id="rex-scripttime"><!--DYN--><?= rex_showScriptTime() ?> Sek | <?= rex_formatter::format(time(), 'strftime', 'date'); ?><!--/DYN--></p>
		</div>
	</div>

	<div id="rex-extra"></div>
	<div id="rex-redaxo-link"><p><a href="./">Wohin verlinke ich?</a></p></div>
</body>
</html>