<?php

global $REX, $SLY, $I18N;

$popups_arr = array('linkmap', 'mediapool');
$config     = sly_Core::config();
$title      = array($config->get('SERVERNAME'), $this->title, $this->subtitle);
$title      = array_map('sly_html', array_filter($title));

$body_id  = str_replace('_', '-', $config->get('PAGE'));
$bodyAttr = 'id="rex-page-'.$body_id.'"';

if (in_array($body_id, $popups_arr)) {
	$bodyAttr .= ' class="rex-popup"';
}

if ($REX['PAGE_NO_NAVI']) {
	$bodyAttr .= ' onunload="closeAll()"';
}

?>
<title><?= implode(' &ndash; ', $title) ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=<?= $this->charset ?>" />
	<link rel="stylesheet" type="text/css" href="media/css_import.css" media="screen, projection, print" />
	<link rel="stylesheet" type="text/css" href="scaffold/import_export/backend.css" media="screen, projection, print" />
	<!--[if lte IE 7]>
	<link rel="stylesheet" href="media/css_ie_lte_7.css" type="text/css" media="screen, projection, print" />
	<![endif]-->

	<!--[if IE 7]>
	<link rel="stylesheet" href="media/css_ie_7.css" type="text/css" media="screen, projection, print" />
	<![endif]-->

	<!--[if lte IE 6]>
	<link rel="stylesheet" href="media/css_ie_lte_6.css" type="text/css" media="screen, projection, print" />
	<![endif]-->
	<script src="media/jquery.min.js" type="text/javascript"></script>
	<script src="media/standard.min.js" type="text/javascript"></script>
	<?= rex_register_extension_point('PAGE_HEADER', '') ?>
