<?php
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

/**
 * Dient zur Ausgabe des Sprachen-Blocks
 *
 * @package redaxo4
 */

$languages = sly_Util_Language::findAll();
$user      = sly_Util_User::getCurrentUser();

if (!isset($curClang) || !sly_Util_Language::exists($curClang)) {
	$curClang = sly_Core::getCurrentClang();
}

if (!isset($params)) {
	$params = array();
}

if (count($languages) > 1) {
	print '
	<div class="sly-clang-toolbar sly-toolbar">
		<div class="sly-toolbar-content">
			<ul>
				<li>'.t('languages').' : </li>';

	$stop = false;
	$i    = 1;

	foreach ($languages as $language) {
		$clangID = $language->getId();

		if ($i == 1) {
			print '<li class="sly-first sly-navi-language-'.$clangID.'">';
		}
		else {
			print '<li class="sly-navi-language-'.$clangID.'">';
		}

		$clangName = sly_translate($language->getName(), true); // contains sly_html()

		if (!sly_Util_Language::hasPermissionOnLanguage($user, $clangID)) {
			print '<span class="sly-na">'.$clangName.'</span>';
			$stop = $clangID == $curClang;
		}
		else {
			$class = '';

			if ($clangID == $curClang) {
				$class = ' class="sly-active"';
			}

			$params['clang'] = $clangID;
			print '<a'.$class.' href="index.php?'.http_build_query($params, '', '&amp;').'">'.$clangName.'</a>';
		}

		print '</li>';
		++$i;
	}

	print '
		</ul>
	</div>
</div>
';

	if ($stop !== false) {
		$lang = sly_Service_Factory::getLanguageService()->findById($stop);
		throw new sly_Authorisation_Exception(t('you_have_no_access_to_this_language', sly_translate($lang->getName())));
	}
}
