<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$user = sly_Util_User::getCurrentUser();

$moduleSelect = new sly_Form_Select_DropDown('add_module', '', '', array(), 'module'.$pos);
$moduleSelect->addClass('sly-module-select');
$moduleSelect->addValue('', '---------------------------- '.t('add_slice'));

foreach ($modules as $module => $moduleTitle) {
	if ($user->isAdmin() || $user->hasRight('module', 'add', $module)) {
		$moduleSelect->addValue($module, sly_translate($moduleTitle));
	}
}

$formID = 'slice'.$pos;

$form = new sly_Form('index.php#slice'.$pos, 'GET', t('add_slice'), $formID, $formID);
$form->addClass('sly-form-add-slice');
$form->addHiddenValue('page', 'content');
$form->addHiddenValue('article_id', $article->getId());
$form->addHiddenValue('clang', $article->getClang());
$form->addHiddenValue('pos', $pos);
$form->addHiddenValue('function', 'add');
$form->addHiddenValue('slot', $slot);

$form->add($moduleSelect);
$form->setSubmitButton(null);
$form->setResetButton(null);
print $form->render();
