<?php
if (!$this->article->hasType())	return;

$typeService = sly_Service_Factory::getArticleTypeService();
$templateService = sly_Service_Factory::getTemplateService();
$templateName = $typeService->getTemplate($this->article->getType());
$hasTemplate = !empty($templateName) && $templateService->exists($templateName);

if (!$hasTemplate) return;

$slots = $templateService->getSlots($templateName);

if (count($slots) < 1) return;

?>
<ul id="rex-navi-slots">
	<li><?= t('content_types') ?></li>
	<?php
	$params['page']       = 'content';
	$params['article_id'] = $this->article->getId();
	$params['clang']      = $this->article->getClang();
	$listElements = array();
	foreach ($slots as $tmpSlot) {
		$params['slot'] = $tmpSlot;
		$class = ($tmpSlot == $this->slot && !($this instanceof sly_Controller_Contentmeta)) ? ' class="rex-active"' : '';
		$slotTitle = rex_translate($templateService->getSlotTitle($templateName, $tmpSlot));

		$listElements[] = '<a href="index.php?' . http_build_query($params) . '"' . $class . '>' . $slotTitle . '</a>';
	}

	$listElements = sly_Core::dispatcher()->filter('SLY_PAGE_CONTENT_SLOT_MENU', $listElements, array(
				'article_id' => $this->article->getId(),
				'clang' => $this->article->getClang()
			));


	foreach ($listElements as $idx => $listElement) {
		?>
		<li><?= $listElement ?></li>
		<?php
	}
	?>
</ul>