<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$baseURL = 'index.php?article_id='.$this->article->getId().'&clang='.$this->article->getClang();
$menu    = '';
$isMeta  = $this instanceof sly_Controller_Contentmeta;

$listElements = array();
$listElements[] = '<a href="'.$baseURL.'&amp;page=content"'.($isMeta ? '' : ' class="sly-active"').'>'.t('edit_mode').'</a>';
$listElements[] = '<a href="'.$baseURL.'&amp;page=contentmeta"'.($isMeta ? ' class="sly-active"' : '').'>'.t('metadata').'</a>';
$listElements[] = '<a href="../'.$this->article->getUrl().'" class="sly-blank">'.t('show').'</a>';

$listElements = sly_Core::dispatcher()->filter('SLY_PAGE_CONTENT_ACTIONS_MENU', $listElements, array(
	'article_id' => $this->article->getId(),
	'clang'      => $this->article->getClang()
));
?>
<ul class="sly-navi-content">
	<?php
	foreach ($listElements as $idx => $element) {
		$class = $idx == 0 ? ' class="sly-first"' : '';
		$menu .= '<li'.$class.'>'.$element.'</li>';
	}

	print $menu;
	?>
</ul>
