<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<?php
$category_id = sly_request('category_id', 'rex-category-id');
$article_id = sly_request('article_id', 'rex-article-id');
$slice_id = sly_request('slice_id', 'rex-slice-id', '');
$function = sly_request('function', 'string');
$slot = sly_request('slot', 'string');
$clang = sly_Core::getCurrentClang();
$languages = sly_Util_Language::findAll();

foreach ($languages as $id => $lang) {
	$languages[$id] = $lang->getName();
}

$article_revision = 0;
$slice_revision = 0;

require SLY_COREFOLDER . '/functions/function_rex_content.inc.php';

// check article's existence
$articleService = sly_Service_Factory::getArticleService();
$article = $articleService->findById($article_id, $clang);

// init services
$typeService = sly_Service_Factory::getArticleTypeService();
$templateService = sly_Service_Factory::getTemplateService();
$moduleService = sly_Service_Factory::getModuleService();
$user = sly_Util_User::getCurrentUser();
$dispatcher = sly_Core::dispatcher();

// Artikel wurde gefunden - Kategorie holen
$category_id = $article->getCategoryId();

// Kategoriepfad und -rechte
// Titel anzeigen
// request params
//$mode     = sly_request('mode', 'string', 'edit');
$function = sly_request('function', 'string');

$hasType = $article->hasType();
$hasTemplate = false;

if ($hasType) {
	$templateName = $typeService->getTemplate($article->getType());
	$hasTemplate = !empty($templateName) && $templateService->exists($templateName);
}

// validate slot

if ($hasTemplate && !$templateService->hasSlot($templateName, $slot)) {
	$slot = $templateService->getFirstSlot($templateName);
}

$curSlots = $hasTemplate ? $templateService->getSlots($templateName) : false;

// Slice add/edit/delete

if ($hasTemplate && $slot !== null && sly_request('save', 'boolean') && in_array($function, array('add', 'edit', 'delete'))) {
	// check module

	if ($function == 'edit' || $function == 'delete') {
		$module = rex_slice_module_exists($slice_id);
	} else { // add
		$module = sly_post('module', 'string');
	}

	if (!$moduleService->exists($module)) {
		$global_warning = t('module_not_found');
		$slice_id = '';
		$function = '';
	} else {
		// Rechte am Modul
		if (!$templateService->hasModule($templateName, $module, $slot)) {
			$global_warning = t('no_rights_to_this_function');
			$slice_id = '';
			$function = '';
		} elseif (!($user->isAdmin() || $user->hasRight('module[' . $module . ']') || $user->hasRight('module[0]'))) {
			$global_warning = t('no_rights_to_this_function');
			$slice_id = '';
			$function = '';
		} else {
			// Daten einlesen
			$REX_ACTION = array('SAVE' => true);

			foreach (sly_Core::getVarTypes() as $idx => $obj) {
				$REX_ACTION = $obj->getACRequestValues($REX_ACTION);
			}

			// ----- PRE SAVE ACTION [ADD/EDIT/DELETE]
			list($action_message, $REX_ACTION) = rex_execPreSaveAction($module, $function, $REX_ACTION);

			// Statusspeicherung für die rex_article Klasse
			$REX['ACTION'] = $REX_ACTION;

			// Werte werden aus den REX_ACTIONS übernommen wenn SAVE=true

			if (!$REX_ACTION['SAVE']) {
				// DONT SAVE/UPDATE SLICE
				if (!empty($action_message)) {
					$warning = $action_message;
				} elseif ($function == 'delete') {
					$warning = t('slice_deleted_error');
				} else {
					$warning = t('slice_saved_error');
				}
			} else {
				// SAVE / UPDATE SLICE

				$sql = sly_DB_Persistence::getInstance();
				$sliceService = sly_Service_Factory::getSliceService();

				if ($function === 'add' || $function === 'edit') {
					$values = array(
						'updatedate' => time(),
						'updateuser' => $user->getLogin()
					);

					if ($function == 'edit') {
						$ooslice = OOArticleSlice::getArticleSliceById($slice_id);
						$realslice = $sliceService->findById($ooslice->getSliceId());
						$realslice->flushValues();
					} else {
						$realslice = $sliceService->create(array('module' => $module));

						$values['prior'] = sly_post('prior', 'int');
						$values['article_id'] = $article_id;
						$values['module'] = $module;
						$values['clang'] = $clang;
						$values['slot'] = $slot;
						$values['revision'] = $slice_revision;
						$values['createdate'] = time();
						$values['createuser'] = $user->getLogin();
					}

					$values['slice_id'] = $realslice->getId();

					// speichern falls nötig
					foreach (sly_Core::getVarTypes() as $obj) {
						$obj->setACValues($realslice->getId(), $REX_ACTION, true, false);
					}

					// fire query
					if ($function === 'edit') {
						$sql->update('article_slice', $values, array('id' => $slice_id));
						rex_deleteCacheSliceContent($realslice->getId());
						$info = $action_message . t('block_updated');
					} else {
						$sql->insert('article_slice', $values);

						$id = $sql->lastId();
						$pre = sly_Core::config()->get('DATABASE/TABLE_PREFIX');
						$info = $action_message . t('block_added');

						$sql->query('UPDATE ' . $pre . 'article_slice SET prior = prior + 1 ' .
								'WHERE article_id = ' . $article_id . ' AND clang = ' . $clang . ' AND slot = "' . $slot . '" ' .
								'AND prior >= ' . $values['prior'] . ' AND id <> ' . $id
						);
					}

					$function = '';
				} else {
					if (rex_deleteArticleSlice($slice_id)) {
						$global_info = t('block_deleted');
					} else {
						$global_warning = t('block_not_deleted');
					}
				}
				// ----- / SAVE SLICE
				// update article
				$value = array('updatedate' => time(), 'updateuser' => $user->getLogin());
				$sql->update('article', $value, array('id' => $article_id, 'clang' => $clang));

				// POST SAVE ACTION [ADD/EDIT/DELETE]

				list($msg, $actions) = rex_execPostSaveAction($module, $function, $REX_ACTION);
				$info .= $msg;
				$dispatcher->notify('SLY_CONTENT_UPDATED', '', compact('article_id', 'clang'));

				// Update Button wurde gedrückt?

				if (sly_post('btn_update', 'string')) {
					$function = 'edit';
				}
			}
		}
	}

	// Flush slice cache
	sly_Core::cache()->flush(OOArticleSlice::CACHE_NS);
}
?>
<div class="sly-content-header">
	<?php
	//navigation
	print $this->render('content/_slotmenu.phtml');
	print $this->render('content/_subpagemenu.phtml');
	?>
</div>
<?php
	//messages
	print $this->render('content/_messages.phtml');
?>
<div class="sly-content-body">
	<?php
	// START: Slice move up/down

	if ($hasTemplate && ($function == 'moveup' || $function == 'movedown')) {
		if ($user->isAdmin() || $user->hasRight('moveSlice[]')) {
			// Modul und Rechte vorhanden?

			$module = rex_slice_module_exists($slice_id);

			if (!$module) {
				// MODUL IST NICHT VORHANDEN
				$warning = t('module_not_found');
				$slice_id = '';
				$function = '';
			} else {
				// RECHTE AM MODUL ?
				if ($user->isAdmin() || $user->hasRight('module[' . $module . ']') || $user->hasRight('module[0]')) {
					list($success, $message) = rex_moveSlice($slice_id, $clang, $function);

					if ($success) {
						$info = $message;
					} else {
						$warning = $message;
					}
				} else {
					$warning = t('no_rights_to_this_function');
				}
			}

			// Flush slice cache
			sly_Core::cache()->flush(OOArticleSlice::CACHE_NS);
		} else {
			$warning = t('no_rights_to_this_function');
		}
	}
	// END: Slice move up/down

	$params = array('id' => $article_id, 'clang' => $clang, 'article' => $article);

	$form = new sly_Form('index.php', 'POST', t('general'), '', 'content_article_form');

	/////////////////////////////////////////////////////////////////
	// init form

	$form->setEncType('multipart/form-data');
	$form->addHiddenValue('page', 'content');
	$form->addHiddenValue('article_id', $this->article->getId());
	$form->addHiddenValue('func', 'setArticleType');
	$form->addHiddenValue('clang', $this->article->getClang());
	$form->addHiddenValue('slot', $this->slot);

	/////////////////////////////////////////////////////////////////
	// articletype
	$types = $typeService->getArticleTypes();
	uasort($types, 'strnatcasecmp');

	$type = new sly_Form_Select_DropDown('article_type', t('content_arttype'), $article->getType(), $types, 'article_type');
	$form->add($type);

	//additional form elements
	$form = sly_Core::dispatcher()->filter('SLY_ART_META_FORM', $form, $params);

	//buttons
	$button = new sly_Form_Input_Button('submit', 'save_article', t('article_save'));
	$form->setSubmitButton($button);

	print $form->render();

	if (!$hasType || !$hasTemplate || $slot === null) {
		if (!$hasType)
			print rex_warning(t('content_select_type'));
		elseif (!$hasTemplate)
			print rex_warning(t('content_configure_article_type'));
		else
			print rex_info(t('content_no_slots'));
	}
	else {
		print '<div class="rex-content-editmode">';
		$prior = sly_request('prior', 'int', 0);

		$articleSlices = OOArticleSlice::getSliceIdsForSlot($article_id, $clang, $slot);

		foreach ($articleSlices as $articleSlice) {
			$ooslice = OOArticleSlice::getArticleSliceById($articleSlice);

			if ($function == 'add' && $prior == $ooslice->getPrior()) {
				$module = sly_request('module', 'string');
				sly_Helper_Content::printAddSliceForm($prior, $module, $article_id, $clang, $slot);
			} else {
				print $this->render('content/_add_slice_form.phtml', array('articleId' => $article_id, 'clangId' => $clang, 'prior' => $ooslice->getPrior(), 'template' => $templateName, 'slot' => $slot));
			}

			if (empty($function) && $prior == $ooslice->getPrior()) {
				if (!empty($info))
					print rex_info($info);
				if (!empty($warning))
					print rex_warning($warning);
			}

			if (($function == 'edit' || $function == 'moveup' || $function == 'movedown') && $slice_id == $ooslice->getId()) {
				if (!empty($info))
					print rex_info($info);
				if (!empty($warning))
					print rex_warning($warning);
			}

			if ($function == 'edit' && $slice_id == $ooslice->getId()) {
				print $this->render('content/_slice_toolbar.phtml', array('articleSlice' => $ooslice));
				sly_Helper_Content::printEditSliceForm($ooslice);
			} else {
				print $this->render('content/_slice_toolbar.phtml', array('articleSlice' => $ooslice));
				print $this->render('content/_slice_content.phtml', array('articleSlice' => $ooslice));
			}
		}

		if ($function == 'add' && $prior == count($articleSlices)) {
			$module = sly_request('module', 'string');
			if (!empty($info))
				print rex_info($info);
			if (!empty($warning))
				print rex_warning($warning);
			sly_Helper_Content::printAddSliceForm($prior, $module, $article_id, $clang, $slot);
		}
		else {
			print $this->render('content/_add_slice_form.phtml', array('articleId' => $article_id, 'clangId' => $clang, 'prior' => count($articleSlices), 'template' => $templateName, 'slot' => $slot));
		}

		print '</div>';
	}
	?>
</div>
