<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $rex_user_loginmessage;

if (!empty($rex_user_loginmessage)) {
	print rex_warning($rex_user_loginmessage);
}
elseif (!empty($this->message)) {
	print rex_warning($this->message);
}

$form = new sly_Form('index.php', 'POST', 'Login', '', 'loginformular');
$form->addHiddenValue('javascript', 0, 'javascript');
$form->addHiddenValue('referer', isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '');

$form->beginFieldset('Login');
$form->add(new sly_Form_Input_Text('rex_user_login', $I18N->msg('login_name'), ''));
$form->add(new sly_Form_Input_Password('rex_user_psw', $I18N->msg('password'), ''));

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', $I18N->msg('login'));
$form->render();

?>

<? if (!empty($rex_user_loginmessage)): ?>
<script type="text/javascript">sly_startLoginTimer('<?= addslashes($I18N->msg('login_welcome')) ?>');</script>
<? endif ?>
