<?php

global $REX, $SLY, $I18N;

if (!empty($this->warning)) print rex_warning($this->warning);
if (!empty($this->info))    print rex_info($this->info);

?>

<div class="rex-form" id="rex-form-specials-languages">
	<form action="index.php#clang" method="post">
		<? if ($this->func == 'add' || $this->func == 'edit'): ?>
		<fieldset>
			<legend><?= $I18N->msg('clang_'.$this->func) ?></legend>
			<input type="hidden" name="page" value="specials" />
			<input type="hidden" name="subpage" value="languages" />
			<input type="hidden" name="clang_id" value="<?= (int) $this->id ?>" />
			<input type="hidden" name="func" value="<?= $this->func ?>" />
		<? endif ?>
		
		<table class="rex-table" summary="" rel="<?= $I18N->msg('delete').'?' ?>">
			<caption><?= $I18N->msg('clang_caption') ?></caption>
			<colgroup>
				<col width="40" />
				<col width="40" />
				<col width="*" />
				<col width="153" />
			</colgroup>
			
			<thead><tr>
				<th class="rex-small"><a class="rex-i-element rex-i-clang-add" href="index.php?page=specials&amp;subpage=languages&amp;func=add#clang"><span class="rex-i-element-text"><?= $I18N->msg('clang_add') ?></span></a></th>
				<th class="rex-small">ID</th>
				<th><?= $I18N->msg('clang_name') ?></th>
				<th><?= $I18N->msg('clang_function') ?></th>
			</tr></thead>
			
			<tbody>
			<?php

			// Add form
			
			if ($this->func == 'add') {
				$name = sly_post('clang_name', 'string');
				$sel  = new rex_select();
				
				$sel->setName('clang_id');
				$sel->setStyle('class="rex-form-select"');
				$sel->setId('rex-form-clang-id');
				$sel->setSize(1);

				foreach (array_diff(range(0, 14), array_keys($REX['CLANG'])) as $clang) {
					$sel->addOption($clang, $clang);
				}
				
				?>
				<tr class="sly-active">
					<td class="rex-small"><span class="rex-i-element rex-i-clang"><span class="rex-i-element-text"><?= sly_html($name) ?></span></span></td>
					<td class="rex-small"><?= $sel->get() ?></td>
					<td><input class="rex-form-text" type="text" name="clang_name" value="<?= sly_html($name) ?>" /></td>
					<td><input class="rex-form-submit" type="submit" name="sly-submit" value="<?= $I18N->msg('clang_add') ?>" /></td>
				</tr>
				<?php
			}
			
			foreach ($SLY['CLANG'] as $langID => $langName) {
				$this->render('views/specials/languages_row.phtml', array(
					'clangID'   => $langID,
					'clangName' => $langName
				));
			}
			
			?>
			</tbody>
		</table>

		<? if ($this->func == 'add' || $this->func == 'edit'): ?>
			<script type="text/javascript">
			<!--
			jQuery('input[name=clang_name]').focus();
			//-->
			</script>
		</fieldset>
		<? endif ?>
	</form>
</div>
