<?php

global $I18N;

$editID  = sly_request('clang_id', 'int');
$add_td  = '';
$add_td  = '';
$delLink = $I18N->msg('clang_delete');

if ($clangID == 0) {
	$delLink = '<span class="sly-strike">'.$delLink.'</span>';
}
else {
	$delLink = '<a href="index.php?page=specials&amp;subpage=languages&amp;func=delete&amp;clang_id='.$clangID.'" class="sly-delete">'.$delLink.'</a>';
}

// Edit form
if ($this->func == 'edit' && $editID == $clangID) {
	$name = sly_post('clang_name', 'string', $clangName);
	
	?>
	<tr class="sly-active">
		<td class="sly-col-a sly-icon"><img src="media/language.png" alt="" class="sly-icon" /></td>
		<td class="sly-col-b"><?= sly_html($clangID) ?></td>
		<td class="sly-col-c"><input class="sly-form-text" type="text" name="clang_name" value="<?= sly_html($name) ?>" /></td>
		<td class="sly-col-d"><input class="sly-form-submit" type="submit" name="sly-submit" value="<?= $I18N->msg('clang_update') ?>" /></td>
	</tr>
	<?php
}
else {
	$editLink = 'index.php?page=specials&amp;subpage=languages&amp;func=edit&amp;clang_id='.$clangID.'#clang';
	
	?>
	<tr>
		<td class="sly-col-a sly-icon"><a href="<?= $editLink ?>"><img src="media/language.png" alt="" class="sly-icon" /></a></td>
		<td class="sly-col-b"><?= sly_html($clangID) ?></td>
		<td class="sly-col-c"><a href="<?= $editLink ?>"><?= sly_html($clangName) ?></a></td>
		<td class="sly-col-d"><?= $delLink ?></td>
	</tr>
	<?php
}
