<?php
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

/**
 * Regelt die Rechte an den einzelnen Kategorien und gibt den Pfad aus
 * Kategorien = Startartikel und Bezüge
 *
 * @package redaxo4
 */

$user = sly_Util_User::getCurrentUser();

$KATPATH = '|'; // Standard für path Eintragungen in DB
$KATPERM = $user->hasPerm('csw[0]') || $user->hasPerm('admin[]');

if (!isset($KATout)) {
	$KATout = ''; // Variable definiert und vorbelegt wenn nicht existent
}

$KAT = new rex_sql();
$KAT->setQuery('SELECT catname, path FROM '.$REX['DATABASE']['TABLE_PREFIX'].'article WHERE id = '.$category_id.' AND startpage = 1 AND clang = '.$clang);

if ($KAT->getRows() != 1) {
	// Kategorie existiert nicht

	if ($category_id != 0) {
		$category_id = 0;
		$article_id  = 0;
	}
}
else {
	$pathElements = trim($KAT->getValue('path'), '|');
	$pathElements = empty($pathElements) ? array(): explode('|', $pathElements);

	// Informationen über den Pfad sammeln

	if (!empty($pathElements)) {
		$path     = implode(',', $pathElements);
		$query    = 'SELECT id, catname FROM '.$REX['DATABASE']['TABLE_PREFIX'].'article WHERE id IN ('.$path.') AND startpage = 1 AND clang = '.$clang;
		$pathData = rex_sql::getArrayEx($query);

		foreach ($pathElements as $catID) {
			$catName = $pathData[$catID];
			$catName = str_replace(' ', '&nbsp;', htmlspecialchars($catName));

			if ($KATPERM || $user->hasPerm('csw['.$catID.']') || $user->hasPerm('csr['.$catID.']'))
			{
				$KATout  .= '<li> : <a href="index.php?page=structure&amp;category_id='.$catID.'&amp;clang='.$clang.'">'.$catName.'</a></li>';
				$KATPATH .= $catID.'|';

				if ($user->hasPerm('csw['.$catID.']')) {
					$KATPERM = true;
				}
			}
		}
	}

	$pathElements = null;
	unset($pathElements);

	if ($KATPERM || $user->hasPerm('csw['.$category_id.']') || $user->hasPerm('csr['.$category_id.']')) {
		$catName = str_replace(' ', '&nbsp;', htmlspecialchars($KAT->getValue('catname')));

		$KATout  .= '<li> : <a href="index.php?page=structure&amp;category_id='.$category_id.'&amp;clang='.$clang.'">'.$catName.'</a></li>';
		$KATPATH .= $category_id.'|';

		if ($user->hasPerm('csw['.$category_id.']')) {
			$KATPERM = true;
		}
	}
	else {
		$category_id = 0;
		$article_id  = 0;
	}
}

$KATout = '
<!-- *** OUTPUT OF CATEGORY-TOOLBAR - START *** -->
<ul class="sly-navi-path">
	<li>'.$I18N->msg('path').'</li>
	<li> : <a href="index.php?page=structure&amp;category_id=0&amp;clang='.$clang.'">Homepage</a></li>
	'.$KATout.'
</ul>
<!-- *** OUTPUT OF CATEGORY-TOOLBAR - END *** -->
';

unset($user);