<?php
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

/**
 * Regelt die Rechte an den einzelnen Kategorien und gibt den Pfad aus
 * Kategorien = Startartikel und Bezüge
 *
 * @package redaxo4
 */

$_user = sly_Util_User::getCurrentUser();

$KATPATH = '|'; // Standard für path Eintragungen in DB
$KATPERM = $_user->hasPerm('csw[0]') || $_user->hasPerm('admin[]');

if (!isset($KATout)) {
	$KATout = ''; // Variable definiert und vorbelegt wenn nicht existent
}

if (!sly_Util_Category::exists($category_id)) {
	// Kategorie existiert nicht

	if ($category_id != 0) {
		$category_id = 0;
		$article_id  = 0;
	}
}
else {
	$KAT = sly_Util_Category::findById($category_id);

	foreach ($KAT->getParentTree() as $parent) {
		if($parent->getId() == $category_id) continue;
		$catName = $parent->getName();
		$catName = str_replace(' ', '&nbsp;', htmlspecialchars($catName));

		if ($KATPERM || $_user->hasPerm('csw['.$parent->getId().']') || $_user->hasPerm('csr['.$parent->getId().']')) {
			$KATout  .= '<li> : <a href="index.php?page=structure&amp;category_id='.$parent->getId().'&amp;clang='.$clang.'">'.$catName.'</a></li>';
			$KATPATH .= $parent->getId().'|';

			if ($_user->hasPerm('csw['.$parent->getId().']')) {
				$KATPERM = true;
			}
		}
	}

	if ($KATPERM || $_user->hasPerm('csw['.$category_id.']') || $_user->hasPerm('csr['.$category_id.']')) {
		$catName = str_replace(' ', '&nbsp;', sly_html($KAT->getCatname()));

		$KATout  .= '<li> : <a href="index.php?page=structure&amp;category_id='.$category_id.'&amp;clang='.$clang.'">'.$catName.'</a></li>';
		$KATPATH .= $category_id.'|';

		if ($_user->hasPerm('csw['.$category_id.']')) {
			$KATPERM = true;
		}
	}
	else {
		$category_id = 0;
		$article_id  = 0;
	}
}

$KATout = '
<!-- *** OUTPUT OF CATEGORY-TOOLBAR - START *** -->
<ul class="sly-navi-path">
	<li>'.t('path').'</li>
	<li> : <a href="index.php?page=structure&amp;category_id=0&amp;clang='.$clang.'">Homepage</a></li>
	'.$KATout.'
</ul>
<!-- *** OUTPUT OF CATEGORY-TOOLBAR - END *** -->
';

unset($_user);
