VERSION: 0
SUBVERSION: 3
MINORVERSION: 10
FILEPERM: 0664
DIRPERM: 0777
SESSION_DURATION: 3000
MOD_REWRITE: true
USE_GZIP: backend
USE_ETAG: never
USE_LAST_MODIFIED: never
TEMP_PREFIX: tmp_
FRONTEND_FILE: index.php
FALLBACK_CACHING_STRATEGY: sly_Cache_Filesystem
RELOGINDELAY: 2
START_PAGE: structure
MEDIAPOOL:
  BLOCKED_EXTENSIONS: [.php, .php3, .php4, .php5, .php6, .phtml, .pl, .asp, .aspx, .cfm, .jsp]
