VERSION: 0
SUBVERSION: 4
MINORVERSION: 0
FILEPERM: 0664
DIRPERM: 0777
SESSION_DURATION: 3000
USE_ETAG: never
USE_LAST_MODIFIED: never
TEMP_PREFIX: tmp_
FRONTEND_FILE: index.php
FALLBACK_CACHING_STRATEGY: BabelCache_Filesystem
RELOGINDELAY: 2
START_PAGE: structure
MEDIAPOOL:
  BLOCKED_EXTENSIONS: [.php, .php3, .php4, .php5, .php6, .phtml, .pl, .asp, .aspx, .cfm, .jsp]
