<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $REX, $I18N;

$config = sly_Core::config();

if (!empty($this->warning)) print rex_warning($this->warning);
if (!empty($this->info))    print rex_info($this->info);

$locales    = array_combine($REX['LOCALES'], $REX['LOCALES']);
$rewrites   = array('true' => 'aktiviert', 'false' => 'deaktiviert');
$tplService = sly_Service_Factory::getService('Template');
$templates  = $tplService->getTemplates();

$backendLocale   = new sly_Form_Select_DropDown('backend_locale', '', $config->get('LANG'), $locales, 'rex-form-lang');
$modRewrite      = new sly_Form_Select_DropDown('mod_rewrite', '', $config->get('MOD_REWRITE') ? 'true' : 'false', $rewrites, 'rex-form-mod-rewrite');
$defaultTemplate = new sly_Form_Select_DropDown('default_template', '', $config->get('DEFAULT_TEMPLATE'), $templates, 'rex-form-default-template-id');
$cachingStrategy = new sly_Form_Select_DropDown('caching_strategy', '', sly_Cache::getStrategy(), sly_Cache::getAvailableCacheImpls(), 'rex-form-caching-strategy');

?>

<div class="rex-form" id="rex-form-system-setup">
	<form action="index.php" method="post">
		<div class="hidden">
			<input type="hidden" name="page" value="specials" />
			<input type="hidden" name="func" value="update" />
		</div>

		<div class="rex-area-col-2">
			<div class="rex-area-col-a">

				<h3 class="rex-hl2"><?= $I18N->msg('specials_features') ?></h3>

				<div class="rex-area-content">
					<h4 class="rex-hl3"><?= $I18N->msg('delete_cache') ?></h4>
					<p class="rex-tx1"><?= $I18N->msg('delete_cache_description') ?></p>
					<p class="rex-button"><a class="rex-button" href="index.php?page=specials&amp;func=clearcache"><?= $I18N->msg('delete_cache') ?></a></p>

					<h4 class="rex-hl3"><?= $I18N->msg('setup') ?></h4>
					<p class="rex-tx1"><?= $I18N->msg('setup_text') ?></p>
					<p class="rex-button"><a class="rex-button" href="index.php?page=specials&amp;func=setup" onclick="return confirm(\'<?= $I18N->msg('setup') ?>?\');"><?= $I18N->msg('setup') ?></a></p>

					<h4 class="rex-hl3"><?= $I18N->msg('version') ?></h4>
					<p class="rex-tx1">SallyCMS <?= $config->get('VERSION') ?>.<?= $config->get('SUBVERSION') ?>.<?= $config->get('MINORVERSION') ?></p>

					<h4 class="rex-hl3"><?= $I18N->msg('database') ?></h4>
					<p class="rex-tx1"><?= $I18N->msg('name') ?>: <?= sly_html($config->get('DATABASE/NAME')) ?><br /><?= $I18N->msg('host') ?>: <?= sly_html($config->get('DATABASE/HOST')) ?></p>
				</div>
			</div>

			<div class="rex-area-col-b">
				<h3 class="rex-hl2"><?= $I18N->msg('specials_settings') ?></h3>

				<div class="rex-area-content">

					<fieldset class="rex-form-col-1">
					<legend><?= $I18N->msg('general_info_header') ?></legend>

					<div class="rex-form-wrapper">
						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-text">
								<label for="rex-form-server">$REX['SERVER']</label>
								<input class="rex-form-text" type="text" id="rex-form-server" name="server" value="<?= sly_html($config->get('SERVER')) ?>" />
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-text">
								<label for="rex-form-servername">$REX['SERVERNAME']</label>
								<input class="rex-form-text" type="text" id="rex-form-servername" name="servername" value="<?= sly_html($config->get('SERVERNAME')) ?>" />
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-text">
								<label for="rex-form-error-email">$REX['ERROR_EMAIL']</label>
								<input class="rex-form-text" type="text" id="rex-form-error-email" name="error_email" value="<?= sly_html($config->get('ERROR_EMAIL')) ?>" />
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-text">
								<label for="rex-form-startarticle-id"><?= t('specials_start_article') ?></label>
								<?php
									$start_article = new sly_Form_LinkButton('start_article', null, $config->get('START_ARTICLE_ID'), 'START_ART');
									print $start_article->render();
								?>
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-text">
								<label for="rex-form-notfound-article-id"><?= t('specials_not_found_article') ?></label>
								<?php
									$start_article = new sly_Form_LinkButton('notfound_article', null, $config->get('NOTFOUND_ARTICLE_ID'), 'NF_ART');
									print $start_article->render();
								?>
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-select">
								<label for="rex-form-default-template-id">$REX['DEFAULT_TEMPLATE']</label>
								<?= $defaultTemplate->render() ?>
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-select">
								<label for="rex-form-lang">$REX['LANG']</label>
								<?= $backendLocale->render() ?>
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-select">
								<label for="rex-form-mod-rewrite">$REX['MOD_REWRITE']</label>
								<?= $modRewrite->render() ?>
							</p>
						</div>
						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-select">
								<label for="rex-form-mod-rewrite"><?= t('specials_caching_strategy') ?></label>
								<?= $cachingStrategy->render() ?>
							</p>
						</div>

						<div class="rex-form-row">
							<p class="rex-form-col-a rex-form-submit">
								<input type="submit" class="rex-form-submit" name="sendit" value="<?= $I18N->msg('specials_update') ?>" />
							</p>
						</div>
					</div>
					</fieldset>
				</div> <!-- Ende rex-area-content //-->
			</div> <!-- Ende rex-area-col-b //-->
		</div> <!-- Ende rex-area-col-2 //-->
	</form>
</div>
