<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title($I18N->msg('setup_step4'));

if (!empty($this->warning)) print rex_warning($this->warning);

$form = new sly_Form('index.php', 'POST', t('setup_0201'), '', 'rex-form-setup-step-4');
$this->printHiddens('config', $form);

// fields

$form->add(new sly_Form_Input_Text('server', t('setup_024'), $server));
$form->add(new sly_Form_Input_Text('servername', t('setup_024'), $serverName));
$form->add(new sly_Form_Input_Text('error_email', t('setup_026'), $errorEMail));

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_049'));

// render it!

$form->setFocus('server');
$form->render();
