<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_step4'));

if (!empty($this->warning)) print rex_warning($this->warning);

$form = new sly_Form('index.php', 'POST', t('setup_045'));
$this->printHiddens('createuser', $form);

// fields

$user = new sly_Form_Input_Text('admin_user', t('setup_046'), $adminUser);

$form->add($user);
$form->add(new sly_Form_Input_Password('admin_pass', t('setup_047')));

if ($usersExist) {
	$form->add(new sly_Form_Input_Checkbox('no_admin', '', '1', t('setup_048')));
	$user->setHelpText('Geben Sie einen bereits bestehenden Benutzernamen ein, um dessen Passwort zu überschreiben.');
}

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_049'));

// render it!

$form->setFocus('admin_user');
$form->render();

if ($usersExist):
?>
<script type="text/javascript">
jQuery(function($) {
	$('#no_admin').change(function() {
		var stat = this.checked;
		$('#admin_user').attr('disabled', stat ? 'disabled' : '');
		$('#admin_pass').attr('disabled', stat ? 'disabled' : '');
	});
});
</script>
<? endif ?>