<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $I18N;

$this->title($I18N->msg('setup_step4'));

?>

<div class="rex-form rex-form-setup-admin">
	<form action="index.php" method="post" autocomplete="off">
		<fieldset class="rex-form-col-1">
			<? $this->printHiddens('createuser') ?>
			<legend><?= $I18N->msg('setup_045') ?></legend>

			<div class="rex-form-wrapper">
				<?php

				if (!empty($this->warning)) {
					print rex_warning($this->warning);
				}

				?>
				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-text">
						<label for="admin_user"><?= $I18N->msg('setup_046') ?>:</label>
						<input class="rex-form-text" type="text" value="<?= sly_html($adminUser) ?>" id="admin_user" name="admin_user" />
					</p>
				</div>

				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-text">
						<label for="admin_pass"><?= $I18N->msg('setup_047') ?>:</label>
						<input class="rex-form-text" type="password" value="" id="admin_pass" name="admin_pass" />
					</p>
				</div>

				<? if ($usersExist): ?>
				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-checkbox rex-form-label-right">
						<input class="rex-form-checkbox" type="checkbox" id="no_admin" name="no_admin" value="1" />
						<label for="no_admin"><?= $I18N->msg('setup_048') ?></label>
					</p>
				</div>
				<? endif ?>

				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-submit">
						<input class="rex-form-submit" type="submit" name="sly-submit" value="<?= $I18N->msg('setup_049') ?>" />
					</p>
				</div>
			</div>
		</fieldset>
	</form>
</div>

<script type="text/javascript">
<!--
jQuery('#admin_user').focus();
//-->
</script>

