<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_step2'));

if (!empty($this->warning)) print rex_warning($this->warning);

$form = new sly_Form('index.php', 'POST', t('setup_0202'), '', 'sly-setup-dbsetup');
$this->printHiddens('dbconfig', $form);

// database driver

$drivers = array('mysql' => 'MySQL', 'pgsql' => 'PostgreSQL', 'oci' => 'Oracle', 'sqlite' => 'SQLite');
$drivers = new sly_Form_Select_DropDown('driver', 'Datenbank-Typ', null, $drivers);
$drivers->setHelpText('Alle Datenbanken außer MySQL sind als hoch experimentell anzusehen und dienen zu Testzwecken!');
$form->add($drivers);

// database infos

$prefix = new sly_Form_Input_Text('prefix', 'Tabellen Präfix', $prefix);
$prefix->setHelpText('Ermöglicht es, mehrere Sally-Installationen in einer Datenbank parallel zu verwalten.');

$form->add(new sly_Form_Input_Text('host', 'Host', $host));
$form->add(new sly_Form_Input_Text('user', 'Login', $user));
$form->add(new sly_Form_Input_Text('pass', t('setup_028'), $pass));

// slightly more complex input for the target database

$dbname = new sly_Form_Input_Text('dbname', t('setup_027'), $dbname);
$create = new sly_Form_Input_Checkbox('create_db', '', '1', t('setup_create_db'));
$name   = new sly_Form_Freeform('dbname', t('setup_027'), $dbname->render().' '.$create->render());

$name->addFormRowClass('rex-form-text'); // so that the styles for the input box apply
$form->add($name);
$form->add($prefix);

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_029'));

// render it!

$form->setFocus('driver');
$form->render();
