<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_finish_title'));

?>
<h2 class="rex-hl2"><?= t('setup_finish_header') ?></h2>
<div class="rex-area-content">
	<h3 class="rex-hl3"><?= t('setup_finish_done') ?></h3>
	<p class="rex-tx1"><?= t('setup_finish_login') ?></p>
	<p class="rex-tx1"><?= nl2br(t('setup_finish_signature')) ?></p>
</div>
