<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_fsperms_title'));

?>

<div class="rex-message" id="security_warning" style="display:none">
	<p class="rex-warning"><span><?= t('setup_fsperms_security_msg') ?></span></p>
</div>

<h2 class="rex-hl2"><?= t('setup_fsperms_header') ?></h2>

<div class="rex-area-content sly-setup-requirements">
	<table summary="">
		<thead><tr>
			<th class="sly-testcase"><?= t('setup_fsperms_property') ?></th>
			<th class="sly-recommended"><?= t('setup_fsperms_recommended') ?></th>
			<th class="sly-status"><?= t('setup_fsperms_status') ?></th>
		</tr></thead>
		<tbody><? foreach ($results as $type => $result): ?><tr class="<?= $tester->getClassName($result[1]) ?>">
			<td class="sly-testcase"><?= rex_translate('translate:setup_fsperms_'.$type) ?></td>
			<td class="sly-recommended"><?= rex_translate($result[0]) ?></td>
			<td class="sly-status"><?= sly_html($result[1]['text']) ?></td>
		</tr><? endforeach ?></tbody>
	</table>
</div>

<? if ($errors): ?>
<div class="rex-area-footer sly-fs-errors">
	<p class="rex-algn-rght"><?= t('setup_fsperms_please_fix') ?></p>
</div>
<? endif ?>

<? if (!empty($cantCreate) || !empty($protects)): ?>
<h2 class="rex-hl2 sly-setup-fs-problems"><?= t('setup_fsperms_fsproblems') ?></h2>
<div class="rex-area-content sly-setup-fs-problems">
	<? if (!empty($cantCreate)): ?>
	<p class="rex-tx1"><?= t('setup_fsperms_cant_access') ?></p>

	<ul class="rex-ul1">
		<li><?= implode('</li><li>', $cantCreate) ?></li>
	</ul>
	<? endif ?>

	<? if (!empty($protects)): ?>
	<p class="rex-tx1"><?= t('setup_fsperms_cant_protect') ?></p>

	<ul class="rex-ul1">
		<li><?= implode('</li><li>', $protects) ?></li>
	</ul>
	<? endif ?>

	<iframe src="include/views/setup/direct.phtml?lang=<?= urlencode($this->lang) ?>" style="display:none"></iframe>
</div>
<? elseif (!$errors): ?>
<div class="rex-area-footer">
	<p id="nextstep" class="rex-algn-rght">
		<a href="index.php?page=setup&amp;func=dbconfig&amp;lang=<?= urlencode($this->lang) ?>">&raquo; <?= t('setup_fsperms_continue') ?></a>
	</p>
</div>
<? endif ?>
