<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$this->title(t('setup_initdb_title'));

// init page

if (!empty($this->warning)) {
	print rex_warning($this->warning.'<br /><br />'.t('setup_initdb_reinit'));
}

if (!in_array($dbInitFunction, $dbInitFunctions)) {
	$dbInitFunction = 'setup';
}

// create form

$form = new sly_Form('index.php', 'POST', t('setup_initdb_header'), '', 'sly-setup-initdb');
$this->printHiddens('initdb', $form);

// create radios for possible init functions

foreach (array('setup', 'drop', 'nop') as $func) {
	$label         = t('setup_initdb_func_'.$func);
	$inputs[$func] = new sly_Form_Input_Radio('db_init_function', '', $func, $label, 'func_'.$func);
}

$inputs['drop']->setHelpText(t('setup_initdb_func_drop_notice'));
$inputs[$dbInitFunction]->setChecked(true);

$inputs = sly_Core::dispatcher()->filter('SLY_SETUP_INIT_FUNCTIONS_FORM', $inputs);
$form->addElements($inputs);

// button config

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('setup_initdb_continue'));

// render it!

$form->render();
