<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $I18N;

$this->title($I18N->msg('setup_step3'));

?>
<div class="rex-form rex-form-setup-step-database">
	<form action="index.php" method="post">
		<fieldset class="rex-form-col-1">
			<? $this->printHiddens('initdb') ?>
			<legend><?= $I18N->msg('setup_030_headline') ?></legend>
			<div class="rex-form-wrapper">
				<?php

				if (!empty($this->warning)) {
					print rex_warning($this->warning.'<br />'.$I18N->msg('setup_033'));
				}

				$checks = array();

				if (!in_array($dbInitFunction, $dbInitFunctions)) {
					$dbInitFunction = 'setup';
				}

				foreach ($dbInitFunctions as $func) {
					$checks[$func] = $dbInitFunction == $func ? ' checked="checked"' : '';
				}

				?>

				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-radio rex-form-label-right">
						<input class="rex-form-radio" type="radio" id="func_setup" name="db_init_function" value="setup"<?= $checks['setup'] ?> />
						<label for="func_setup"><?= $I18N->msg('setup_034') ?></label>
					</p>
				</div>

				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-radio rex-form-label-right">
						<input class="rex-form-radio" type="radio" id="func_drop" name="db_init_function" value="drop"<?= $checks['drop'] ?> />
						<label for="func_drop"><?= $I18N->msg('setup_035', '<b>', '</b>') ?></label>
					</p>
				</div>

				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-radio rex-form-label-right">
						<input class="rex-form-radio" type="radio" id="func_nop" name="db_init_function" value="nop"<?= $checks['nop'] ?> />
						<label for="func_nop"><?= $I18N->msg('setup_036') ?></label>
					</p>
				</div>

				<? rex_register_extension_point('SLY_SETUP_INIT_FUNCTIONS_FORM', $dbInitFunction); ?>

			</div>
		</fieldset>

		<fieldset class="rex-form-col-1">
			<div class="rex-form-wrapper">
				<div class="rex-form-row">
					<p class="rex-form-col-a rex-form-submit">
						<input class="rex-form-submit" type="submit" name="sly-submit" value="<?= $I18N->msg('setup_039') ?>" />
					</p>
				</div>
			</div>
		</fieldset>
	</form>
</div>

