<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

global $REX, $I18N;

$this->title('SETUP: START');

$REX['LANG'] = $this->lang;

print $I18N->msg('setup_005', '<h2 class="rex-hl2">', '</h2>');
print '<div class="rex-area-content">';

print $I18N->msg('setup_005_1', '<h3 class="rex-hl3">', '</h3>', ' class="rex-ul1"');
print '<div class="rex-area-scroll">';

$basedir = $REX['FRONTEND_PATH'];
$license = '<p class="rex-tx1">'.nl2br(file_get_contents($basedir.'/_lizenz.txt')).'</p>';

print $license;

?>
	</div>
</div>

<div class="rex-area-footer">
	<p class="rex-algn-rght"><a href="index.php?page=setup&amp;func=fsperms&amp;lang=<?= urlencode($this->lang) ?>">&raquo; <?= $I18N->msg('setup_006') ?></a></p>
</div>
