<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$artID    = $this->getDisplayValue();
$art      = sly_Util_Article::findById($artID);
$artName  = '';
$category = '';
$name     = sly_html($this->attributes['name']);

if (sly_Util_Article::isValid($art)) {
	$artName  = sly_html($art->getName());
	$category = $art->getCategoryId();
}

?>

<span class="sly-widget sly-linkbutton" data-id="<?= $name ?>" data-catid="<?= $category ?>">
	<input type="hidden" name="<?= $name ?>" id="<?= $name ?>" value="<?= sly_html($artID) ?>" />
	<input type="text" value="<?= $artName ?>" class="<?= sly_html($this->attributes['class']) ?>" readonly="readonly" />

	<span class="sly-icons">
		<a href="#" rel="open"><img src="assets/file_open.png" title="<?= t('open_linkmap') ?>" alt="" /></a>
		<a href="#" rel="delete"><img src="assets/file_del.png" title="<?= t('remove_link') ?>" alt="" /></a>
	</span>
</span>
