<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id       = $this->getWidgetID();
$art      = sly_Util_Article::findById($this->getDisplayValue());
$artName  = '';
$category = '';
$params   = '';

if (sly_Util_Article::isValid($art)) {
	$artName  = sly_html($art->getName());
	$category = $art->getCategoryId();

	if ($category) {
		$params = '&amp;category_id='.$category;
	}
}

$this->consumeWidgetID();

?>

<span class="sly-widget sly-linkbutton">
	<input type="hidden" name="<?= sly_html($this->attributes['name']) ?>" id="LINK_<?= $id ?>" value="<?= sly_html($this->attributes['value']) ?>" />
	<input type="text" name="LINK_NAME[<?= $id ?>]" value="<?= $artName; ?>" class="<?= sly_html($this->attributes['class']) ?>" id="LINK_<?= $id ?>_NAME" readonly="readonly" />

	<span class="sly-icons">
		<a href="#" onclick="openLinkMap('LINK_<?= $id ?>', '<?= $params ?>'); return false;"><img src="assets/file_open.png" title="<?= t('open_linkmap') ?>" alt="" /></a>
		<a href="#" onclick="deleteREXLink('<?= $id ?>'); return false;"><img src="assets/file_del.png" title="<?= t('remove_link') ?>" alt="" /></a>
	</span>
</span>
