<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id    = $this->getWidgetID();
$files = sly_makeArray($this->getDisplayValue());
$files = empty($files) ? array() : array_filter($files);

$this->consumeWidgetID();

?>
<span class="sly-widget sly-medialistbutton">
	<input type="hidden" name="<?= $this->attributes['name'] ?>" id="REX_MEDIALIST_<?= $id ?>" value="<?= sly_html(implode(',', (array)$this->attributes['value'])) ?>" />
	<select id="REX_MEDIALIST_SELECT_<?= $id ?>" size="8" class="<?= $this->attributes['class'] ?>">
		<?php
			foreach($files as $file) {
				printf('<option value="%s">%s</option>', $file, $file);
			}
		?>
	</select>
	<span class="sly-icons">
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'top'); return false;"><img src="assets/file_top.png" title="<?= t('var_medialist_move_top') ?>" alt="" /></a>
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'up'); return false;"><img src="assets/file_up.png" title="<?= t('var_medialist_move_up') ?>" alt="" /></a>
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'down'); return false;"><img src="assets/file_down.png" title="<?= t('var_medialist_move_down') ?>" alt="" /></a>
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'bottom'); return false;" style="margin-right:2em"><img src="assets/file_bottom.png" title="<?= t('var_medialist_move_bottom') ?>" alt="" /></a>
	</span>

	<span class="sly-icons">
		<a href="#" onclick="openREXMedialist(<?= $id ?>); return false;"><img src="assets/file_open.png" title="<?= t('var_media_open') ?>" alt="" /></a>
		<a href="#" onclick="addREXMedialist(<?= $id ?>); return false;"><img src="assets/file_add.png" title="<?= t('var_media_new') ?>" alt="" /></a>
		<a href="#" onclick="deleteREXMedialist(<?= $id ?>); return false;"><img src="assets/file_del.png" title="<?= t('var_media_remove') ?>" alt="" /></a>
	</span>
</span>
