<?
/**
 * Folgende Datentypen sind möglich:
 *
 * string => strtotime($value)    (alles, was PHP als Zeitangabe versteht)
 * int    => intval($value)       (UNIX-Timestamp)
 * false  => time()               (jetzt)
 * null   => ''                   (kein Datum ausgeben)
 */

global $I18N;

$name     = $this->getAttribute('name');
$id       = $this->getAttribute('id');
$minYear  = 1970; // Und es machte Booom im UNIX-Universum...
$maxYear  = date('Y') + 20;
$value    = $this->attributes['value'];

if ($value === false) {
	$value = time();
}

if ($value !== null) {
	$value = sly_Util_String::isInteger($value) ? intval($value) : strtotime($value);
}

// JavaScript-Version

$dateformat = $I18N->msg('dateformat');
$formatJS   = $dateformat;
$formatJS   = str_replace(
	array('%a', '%A', '%d', '%e', '%j', '%b', '%B', '%h', '%m', '%y', '%Y'),
	array('D',  'DD', 'dd', 'd',  'oo', 'M',  'MM', 'M',  'mm', 'y',  'yy'),
	$formatJS);

$attrs['class'] = 'rex-form-text';
$attrs['type']  = 'text';
$attrs['name']  = sly_html($name).'_date';
$attrs['id']    = $attrs['name'];
$attrs['style'] = 'width:150px';
$attrs['value'] = $value === null ? '' : strftime($dateformat.($this->withTime() ? ' %H:%M' : ''), $value);

print '<input '.sly_Util_HTML::buildAttributeString($attrs).' />';

$registry = sly_Core::getTempRegistry();
$locale   = $I18N->msg('htmllang');

if (!$registry->has('sly.form.datetime.links')) {
	$path   = 'media/js/';
	$layout = sly_Core::getLayout();

	$layout->addCSSFile($path.'jqueryui-theme/jqueryui.min.css');

	$layout->addJavaScriptFile($path.'jqueryui.core.min.js');
	$layout->addJavaScriptFile($path.'jqueryui.datepicker.min.js');
	$layout->addJavaScriptFile($path.'jqueryui.effects.min.js');

	if ($this->withTime()) {
		$layout->addJavaScriptFile($path.'jqueryui.mouse.min.js');
		$layout->addJavaScriptFile($path.'jqueryui.slider.min.js'); // widget ist im Core enthalten
		$layout->addJavaScriptFile($path.'jquery.timepicker.min.js');
	}

	$registry->set('sly.form.datetime.links', true);
}

// Die userLang dient dazu, dass PHP auch ohne korrekt gesetztes Locale das
// Datum richtig parsen kann.

?>

<script type="text/javascript">
jQuery(function($) {
<? if ($this->withTime()): ?>
	$('#<?= sly_html($name) ?>_date').datetime({
		dateFormat: '<?= addslashes($formatJS) ?>',
		userLang: '<?= $locale ?>'
	});
<? else: ?>
	$('#<?= sly_html($name) ?>_date').datepicker({dateFormat: '<?= addslashes($formatJS) ?>'});
<? endif ?>
});
</script>
