<?
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

if (!empty($this->hiddenValues)) print '<div>';
foreach ($this->hiddenValues as $name => $value) {
	print '<input type="hidden" name="'.sly_html($name).'" value="'.sly_html($value['value']).'"';
	if (!empty($value['id'])) print ' id="'.sly_html($value['id']).'"';
	print ' />'.PHP_EOL;
}
if (!empty($this->hiddenValues)) print '</div>';

$elementCount = count($this->elements);

foreach ($this->elements as $x => $element) {
	$isLast = $x-1 == $elementCount;
	include 'element.phtml';
}
