<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$id    = $this->getWidgetID();
$files = sly_makeArray($this->getDisplayValue());
$files  = empty($files) ? array() : array_filter($files);

$this->consumeWidgetID();

?>
<span class="sly-widget sly-medialistbutton">
	<input type="hidden" name="<?= $this->attributes['name'] ?>" id="REX_MEDIALIST_<?= $id ?>" value="<?= sly_html(implode(',', (array)$this->attributes['value'])) ?>" />
	<select id="REX_MEDIALIST_SELECT_<?= $id ?>" size="8" class="<?= $this->attributes['class'] ?>">
		<?php
			foreach($files as $file) {
				printf('<option value="%s">%s</option>', $file, $file);
			}
		?>
	</select>
	<span class="sly-icons">
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'top'); return false;"><img src="media/file_top.gif" title="Ganz Hoch schieben" alt="Ganz Hoch schieben" /></a>
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'up'); return false;"><img src="media/file_up.gif" title="Hoch schieben" alt="Hoch schieben" /></a>
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'down'); return false;"><img src="media/file_down.gif" title="Runter schieben" alt="Runter schieben" /></a>
		<a href="#" onclick="moveREXMedialist(<?= $id ?>, 'bottom'); return false;" style="margin-right:2em"><img src="media/file_bottom.gif" title="Ganz runter schieben" alt="Ganz runter schieben" /></a>
	</span>

	<span class="sly-icons">
		<a href="#" onclick="openREXMedialist(<?= $id ?>); return false;"><img src="media/file_open.gif" title="Medium öffnen" alt="Medium öffnen" /></a>
		<a href="#" onclick="addREXMedialist(<?= $id ?>); return false;"><img src="media/file_add.gif" title="Medium hinzufügen" alt="Medium hinzufügen" /></a>
		<a href="#" onclick="deleteREXMedialist(<?= $id ?>); return false;"><img src="media/file_del.gif" title="Medium entfernen" alt="Medium entfernen" /></a>
	</span>
</span>
