<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

// Daten vorbereiten

$label     = $I18N->msg($this->func == 'edit' ? 'edit_user' : 'create_user');
$currentID = $REX['USER']->getValue('id');
$PERM      = $REX['PERM'];
$EXTPERM   = empty($REX['EXTPERM']) ? array() : $REX['EXTPERM'];
$EXTRAPERM = empty($REX['EXTRAPERM']) ? array() : $REX['EXTRAPERM'];
$rights    = $user ? $user->getRightsAsArray() : array();

//////////////////////////////////////////////////////////////////
// start the form

$form = new sly_Form('index.php', 'POST', '');
$form->addHiddenValue('page', 'user');
$form->addHiddenValue('save', '1');
$form->addHiddenValue('func', $this->func);
$form->addHiddenValue('id', $user ? $user->getId() : 0);

//////////////////////////////////////////////////////////////////
// first row: login and password

if ($user) {
	$login = new sly_Form_Text($I18N->msg('login_name'), $user->getLogin());
}
else {
	$login = new sly_Form_Input_Text('userlogin', $I18N->msg('login_name'), '');
}

$password = new sly_Form_Input_Text('userpsw', $I18N->msg('password'), '');
$password->setHelpText($I18N->msg('psw_encrypted'));

$form->beginFieldset($label, '', 2);
$form->addRow(array($login, $password));

//////////////////////////////////////////////////////////////////
// second row: name and description

$name        = new sly_Form_Input_Text('username', $I18N->msg('name'), $user ? $user->getName() : '');
$description = new sly_Form_Input_Text('userdesc', $I18N->msg('description'), $user ? $user->getDescription() : '');

$form->addRow(array($name, $description));

//////////////////////////////////////////////////////////////////
// third row: admin and status

$userAdmin  = new sly_Form_Input_Checkbox('is_admin', '', '1', $I18N->msg('user_admin'));
$userStatus = new sly_Form_Input_Checkbox('userstatus', '', '1', $I18N->msg('user_status'));

$userAdmin->addOuterClass('rex-form-label-right');
$userStatus->addOuterClass('rex-form-label-right');

if ($user) {
	$userAdmin->setChecked($user->isAdmin());
	$userStatus->setChecked($user->getStatus());

	if ($currentID == $user->getId()) {
		$userAdmin->setDisabled(true);
		$userStatus->setDisabled(true);
	}
}

$form->addRow(array($userAdmin, $userStatus));

//////////////////////////////////////////////////////////////////
// fourth row: language access and backend locale

$allowedCLangs = $user ? $user->getAllowedCLangs() : array();
$backendLocale = $user ? $user->getBackendLocale() : array();
$clangSelect   = new sly_Form_Select_DropDown('userperm_sprachen', $I18N->msg('user_lang_xs'), $allowedCLangs, $REX['CLANG'], 'userperm-sprachen');
$localeSelect  = new sly_Form_Select_DropDown('userperm_mylang', $I18N->msg('backend_language'), $backendLocale, $this->getBackendLocales(), 'userperm-mylang');

$localeSelect->setMultiple(false);
$clangSelect->setSize(3);
$clangSelect->setHelpText($I18N->msg('ctrl'));

$form->addRow(array($clangSelect, $localeSelect));

//////////////////////////////////////////////////////////////////
// fifth row: backend startpage

$startPage       = $user ? $user->getStartPage() : array();
$startpageSelect = new sly_Form_Select_DropDown('userperm_startpage', $I18N->msg('startpage'), $startPage, $this->getPossibleStartpages(), 'userperm-startpage');

$startpageSelect->setMultiple(false);
$form->addRow(array($startpageSelect));

//////////////////////////////////////////////////////////////////
// sixth row: permissions

sort($PERM);
sort($EXTPERM);
sort($EXTRAPERM);

$extPermSelect = new sly_Form_Select_DropDown('userperm_ext', '', $rights, array_combine($EXTPERM, $EXTPERM), 'userperm-ext');
$allPermSelect = new sly_Form_Select_DropDown('userperm_all', '', $rights, array_combine($PERM, $PERM), 'userperm-all');

$extPermSelect->setSize(10);
$allPermSelect->setSize(10);
$extPermSelect->setHelpText($I18N->msg('ctrl'));
$allPermSelect->setHelpText($I18N->msg('ctrl'));

$form->addRow(array($allPermSelect, $extPermSelect));

//////////////////////////////////////////////////////////////////
// seventh row: cats checkboxes

$allCats      = new sly_Form_Input_Checkbox('userperm_cat_all', '', '1', $I18N->msg('all_categories'));
$allMediaCats = new sly_Form_Input_Checkbox('userperm_media_all', '', '1', $I18N->msg('all_mediafolder'));

$allCats->addOuterClass('rex-form-label-right');
$allMediaCats->addOuterClass('rex-form-label-right');

if ($user) {
	$allCats->setChecked($user->hasRight('csw[0]'));
	$allMediaCats->setChecked($user->hasRight('media[0]'));
}

$form->addRow(array($allCats, $allMediaCats));

//////////////////////////////////////////////////////////////////
// eigth row: category selects

$allowedCategories      = $user ? $user->getAllowedCategories() : array();
$allowedMediaCategories = $user ? $user->getAllowedMediaCategories() : array();

$categorySelect = new sly_Form_Select_DropDown('userperm_cat', $I18N->msg('categories'), $allowedCategories, $this->getStructure(), 'userperm_cat');
$mediaCatSelect = new sly_Form_Select_DropDown('userperm_media', $I18N->msg('mediafolder'), $allowedMediaCategories, $this->getMediaStructure(), 'userperm_media');

$categorySelect->setSize(20);
$mediaCatSelect->setSize(20);
$categorySelect->setHelpText($I18N->msg('ctrl'));
$mediaCatSelect->setHelpText($I18N->msg('ctrl'));

$form->addRow(array($categorySelect, $mediaCatSelect));

//////////////////////////////////////////////////////////////////
// nineth row: misc

$allowedModules  = $user ? $user->getAllowedModules() : array();
$moduleSelect    = new sly_Form_Select_DropDown('userperm_module', $I18N->msg('modules'), $allowedModules, $this->getModules(), 'userperm-module');
$extraPermSelect = new sly_Form_Select_DropDown('userperm_extra', $I18N->msg('extras'), $rights, array_combine($EXTRAPERM, $EXTRAPERM), 'userperm-extra');

$moduleSelect->setSize(10);
$extraPermSelect->setSize(10);
$moduleSelect->setHelpText($I18N->msg('ctrl'));
$extraPermSelect->setHelpText($I18N->msg('ctrl'));

$form->addRow(array($moduleSelect, $extraPermSelect));

//////////////////////////////////////////////////////////////////
// Finally, render it!

$form->setSubmitButton(null);
$form->setResetButton(null);

if ($user) {
	$form->addRow(array(
		new sly_Form_ButtonBar(array('submit' => new sly_Form_Input_Button('submit', 'submit', $I18N->msg('user_save')))),
		new sly_Form_ButtonBar(array('apply' => new sly_Form_Input_Button('submit', 'apply', $I18N->msg('user_apply'))))
	));
}
else {
	$form->addRow(array(
		new sly_Form_ButtonBar(array('submit' => new sly_Form_Input_Button('submit', 'submit', $I18N->msg('add_user'))))
	));
}

$form->render();
