<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * Diese Datei steht unter der MIT-Lizenz. Der Lizenztext befindet sich in der
 * beiliegenden LICENSE Datei und unter:
 *
 * http://www.opensource.org/licenses/mit-license.php
 * http://de.wikipedia.org/wiki/MIT-Lizenz
 */

global $I18N, $REX;

$base   = 'index.php?page=user&amp;func=';
$thIcon = '<a href="'.$base.'add"><img class="sly-icon sly-sprite sly-user-add" alt="" src="media/empty.png" title="'.$I18N->msg('create_user').'" /></a>';
$table  = new sly_Table('users');

$table->addColumn(new sly_Table_Column($thIcon, '', '', array('class' => 'rex-icon')));
$table->addColumn(new sly_Table_Column('ID', '25px'));
$table->addColumn(new sly_Table_Column($I18N->msg('name')));
$table->addColumn(new sly_Table_Column($I18N->msg('login')));
$table->addColumn(new sly_Table_Column($I18N->msg('last_login'), '150px'));
$table->addColumn(new sly_Table_Column($I18N->msg('user_delete'), '150px'));

$table->setIsEmpty(false);
$table->renderHeader(count($users));

$tdIcon    = '';
$currentID = $REX['USER']->getValue('id');

foreach ($users as $user) {
	$id    = (int) $user->getId();
	$name  = $user->getName();
	$login = $user->getLogin();
	
	if (empty($name)) {
		$name = $login;
	}
	
	?>
	<tr>
		<td class="sly-col-a sly-icon">
			<a href="<?= $base ?>edit&amp;id=<?= $id ?>">
				<img src="media/empty.png" class="sly-icon sly-sprite sly-user" alt="" title="<?= sly_html($login) ?>" />
			</a>
		</td>
		<td class="sly-col-b sly-center"><?= $id ?></td>
		<td class="sly-col-c"><a href="<?= $base ?>edit&amp;id=<?= $id ?>"><?= sly_html($name) ?></a></td>
		<td class="sly-col-d"><?= sly_html($user->getLogin()) ?></td>
		<td class="sly-col-e"><?= rex_formatter::format($user->getLastTryDate(), 'strftime', 'datetime') ?></td>
		
		<? if ($id == $currentID): ?>
		<td class="sly-col-f"><span class="rex-strike"><?= $I18N->msg('user_delete') ?></span></td>
		<? else: ?>
		<td class="sly-col-f"><a class="sly-action sly-delete" href="<?= $base ?>delete&amp;id=<?= $id ?>"><?= $I18N->msg('user_delete') ?></a></td>
		<? endif ?>
	</tr>
	<?
}

$table->renderFooter();
