<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

if (!empty($info))    print rex_info($info);
if (!empty($warning)) print rex_warning($warning);

print_r($_POST);

$form = new sly_Form('index.php?page=addon', 'POST', 'Testformular');

$range = new sly_Form_Input_Range('foo', 'Range');
$range->setBounds(0, 100, 4);
$form->add($range);

$range = new sly_Form_Input_Number('foo2', 'Number');
$range->setBounds(0, 100, 4);
$form->add($range);

$range = new sly_Form_Input_Email('foo3', 'Email');
$form->add($range);

$range = new sly_Form_DateTime('foo4', 'Email', time());
$form->add($range);

print $form->render();

?>
<table class="rex-table sly-addonlist">
	<caption><?= t('addon_caption') ?></caption>
	<colgroup>
		<col width="40" />
		<col width="*"/>
		<col width="120" />
		<col width="120" />
		<col width="120" />
		<col width="120" />
	</colgroup>
		<thead>
			<tr>
				<th class="sly-icon rex-col-a">&nbsp;</th>
				<th class="rex-col-b"><?= t('addon_hname') ?></th>
				<th class="rex-col-c"><?= t('addon_hinstall') ?></th>
				<th class="rex-col-d"><?= t('addon_hactive') ?></th>
				<th class="rex-col-e"><?= t('addon_hassets') ?></th>
				<th class="rex-col-f"><?= t('addon_hdelete') ?></th>
			</tr>
		</thead>
	<tbody>

	<?php

	$addonList = $addons->getRegisteredAddOns();

	foreach ($addonList as $addon) {
		$base              = 'index.php?page=addon&amp;addon='.urlencode($addon).'&amp;func=';
		$registeredPlugins = $plugins->getRegisteredPlugins($addon);
		$availablePlugins  = $plugins->getAvailablePlugins($addon);
		$isRequired        = $addons->isActivated($addon) ? $addons->isRequired($addon) : false;
		$required          = $isRequired ? sly_html(t('is_required', is_array($isRequired) ? reset($isRequired).'/'.end($isRequired) : $isRequired)) : '';
		$classes           = array('sly-addon');

		if (!empty($registeredPlugins)) {
			$classes[] = 'sly-has-plugins';
		}

		if ($addons->isInstalled($addon)) {
			$install   = t('addon_yes').' - <a href="'.$base.'install">'.t('addon_reinstall').'</a>';
			$classes[] = 'sly-installed';

			if (!empty($availablePlugins)) {
				$uninstall = t('plugin_plugins_installed');
				$classes[] = 'sly-has-active-plugins';
			}
			elseif ($isRequired) {
				$uninstall = '<del title="'.$required.'">'.t('addon_uninstall').'</del>';
			}
			else {
				$uninstall = '<a href="'.$base.'uninstall" onclick="return confirm(\''.sly_html(t('addon_uninstall_question', $addon)).'\');">'.t('addon_uninstall').'</a>';
			}
		}
		else {
			$install   = t('addon_no').' - <a href="'.$base.'install">'.t('addon_install').'</a>';
			$uninstall = t('addon_notinstalled');
			$classes[] = 'sly-not-installed';
		}

		if ($addons->isActivated($addon)) {
			$status    = t('addon_yes').($isRequired ? ' - <del title="'.$required.'">'.t('addon_deactivate').'</del>' : ' - <a href="'.$base.'deactivate">'.t('addon_deactivate').'</a>');
			$classes[] = 'sly-activated';
			$assets    = '<a href="'.$base.'assets">'.t('addon_reinit_assets').'</a>';
		}
		elseif ($addons->isInstalled($addon)) {
			$status = t('addon_no').' - <a href="'.$base.'activate">'.t('addon_activate').'</a>';
			$assets = '<a href="'.$base.'assets">'.t('addon_reinit_assets').'</a>';
		}
		else {
			$status = t('addon_notinstalled');
			$assets = $status;
		}

		?>
		<tr class="<?= implode(' ', $classes) ?>">
			<td class="sly-icon rex-col-a"><?= sly_Util_HTML::getSpriteLink('', $addon, 'addon') ?></td>
			<td class="rex-col-b"><a href="index.php?page=addon&amp;subpage=help&amp;addon=<?= urlencode($addon) ?>"><?= sly_html($addon) ?></a></td>
			<td class="rex-col-c"><?= $install ?></td>
			<td class="rex-col-d"><?= $status ?></td>
			<td class="rex-col-e"><?= $assets ?></td>
			<td class="rex-col-f"><?= $uninstall ?></td>
		</tr>
		<?php

		if ($addons->isAvailable($addon)) {
			foreach ($registeredPlugins as $plugin) {
				$comp    = array($addon, $plugin);
				$base    = 'index.php?page=addon&amp;addon='.urlencode($addon).'&amp;plugin='.urlencode($plugin).'&amp;func=';
				$classes = array('sly-plugin');

				if ($plugins->isInstalled($comp)) {
					$install   = t('addon_yes').' - <a href="'.$base.'install">'.t('addon_reinstall').'</a>';
					$uninstall = '<a href="'. $base .'uninstall" onclick="return confirm(\''.sly_html(t('plugin_uninstall_question', $addon)).'\');">'.t('addon_uninstall').'</a>';
					$classes[] = 'sly-installed';
				}
				else {
					$install   = t('addon_no').' - <a href="'.$base.'install">'.t('addon_install').'</a>';
					$uninstall = t('addon_notinstalled');
					$classes[] = 'sly-not-installed';
				}

				if ($plugins->isActivated($comp)) {
					$status    = t('addon_yes').' - <a href="'.$base.'deactivate">'.t('addon_deactivate').'</a>';
					$classes[] = 'sly-activated';
					$assets    = '<a href="'.$base.'assets">'.t('addon_reinit_assets').'</a>';
				}
				elseif ($plugins->isInstalled($comp)) {
					$status = t('addon_no').' - <a href="'.$base.'activate">'.t('addon_activate').'</a>';
					$assets = '<a href="'.$base.'assets">'.t('addon_reinit_assets').'</a>';
				}
				else {
					$status = t('addon_notinstalled');
					$assets = $status;
				}

				?>
				<tr class="<?= implode(' ', $classes) ?>">
					<td class="sly-icon rex-col-a"><span class="rex-i-element rex-i-plugin"><span class="rex-i-element-text"><?= sly_html($plugin) ?></span></span></td>
					<td class="rex-col-b"><a href="index.php?page=addon&amp;subpage=help&amp;addon=<?= urlencode($addon) ?>&amp;plugin=<?= urlencode($plugin) ?>"><?= sly_html($plugin) ?></a></td>
					<td class="rex-col-c"><?= $install ?></td>
					<td class="rex-col-d"><?= $status ?></td>
					<td class="rex-col-e"><?= $assets ?></td>
					<td class="rex-col-f"><?= $uninstall ?></td>
				</tr>
				<?php
			}
		}
	}

	if (empty($addonList)) {
		?>
		<tr>
			<td class="rex-col-a center" colspan="5"><?= t('addon_empty_list') ?></td>
		</tr>
		<?php
	}

	?>
	</tbody>
</table>
